### ISSUE TITLE
Catalyst StackOverflowError for large Vector{Reaction}

### ISSUE THREAD

**Issue by sebapersson** [SciML/Catalyst.jl#1080]
**Describe the bug 🐞**

In SBMLImporter, when we parse a model into a Catalyst `ReactionSystem` we first parse the reactions into a `Vector{Reaction}`. For large model (> 50000 reactions), creating a `Vector{Reaction}` triggers a `StackOverflowError`. I can work around this using `addreaction!`, but as it was dropped in v14 this is not ideal.

**Expected behavior**

No `StackOverflowError`.

**Minimal Reproducible Example 👇**

Creating a small MRE is not really possible in this case. I have created a file that triggers this error (note, this file is large due to the huge `Catalyst.Reaction` vector). The file is available here: 
[SBML_model.zip](https://github.com/user-attachments/files/17431281/SBML_model.zip)

**Error & Stacktrace ⚠️**

```julia
ERROR: LoadError: StackOverflowError:
Stacktrace:
 [1] include(fname::String)
   @ Main ./sysimg.jl:38
 [2] top-level scope
   @ REPL[3]:1
in expression starting at /home/sebpe/.julia/dev/SBMLImporter/test/SBML_model.jl:7
```

**Environment (please complete the following information):**

Using latest versions of SBMLImporter.jl and Catalyst.jl is enough to trigger the issue.

**Comment by isaacsas** [comment]
Where is it crashing? Just making the vector, calling `ReactionSystem`, converting to ODEs, etc?

**Comment by sebapersson** [comment]
Just making the Vector. I think if the `Vector` can be made, everything else should work.

**Comment by isaacsas** [comment]
I don't see such issues at all:
```julia
using Catalyst
rx = @reaction k*D, 2*A + 3*B --> C
v = []
for i = 1:1000000
    push!(v, deepcopy(rx))
end
```
This takes a few seconds, but otherwise seems to work fine.

Are you sure there isn't something else going on? I wouldn't think a large vector should even cause a StackOverFlow error since it shouldn't be on the stack.

**Comment by isaacsas** [comment]
@ChrisRackauckas is there any reason creating a `Vector` could cause a StackOverFlow error?

**Comment by isaacsas** [comment]
@sebapersson can you point me to the specific function in which this is crashing so I can take a look?

**Comment by isaacsas** [comment]
Looking at your file, I think the issue is your vector is too big of an expression for Julia to input (i.e. the "one line of code" representing the vector is just too long). We have seen this problem with MTK in the past, where if one has too many ODEs the generated ODE rhs function won't compile and you get a StackOverFlow error (i.e. it is just too much code for the compiler to handle since program code lives on the stack).

You need a different approach for building your vector than listing all the entries at once. For example, add each entry one at a time via `push!` or in blocks with `append!`.

**Comment by isaacsas** [comment]
And you probably can't have a single function that actually includes a line of code adding each of these individual reactions, as it will likely also be too large.

**Comment by sebapersson** [comment]
Thanks for the feedback, I will try to see what happens if I build the `Vector` sequentially with `push!`

**Comment by isaacsas** [comment]
Let us know if that fixes this! Happy to help more if it doesn't.

**Comment by sebapersson** [comment]
Using `push!` fixes the problem. Thanks for the help!

**Comment by isaacsas** [comment]
Awesome!
