### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/Catalyst.jl#127]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by korsbo** [comment]
@JuliaRegistrator register()

**Comment by korsbo** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
Oh, this probably should have been a breaking release since it included @TorkelE’s changing of the parameter orderings…

**Comment by isaacsas** [comment]
That’s going to get us user complaints…

**Comment by ChrisRackauckas** [comment]
Yeah tagbot only shows patch PRs?

**Comment by isaacsas** [comment]
Ahh, I missed that we had 10.3. That probably should have been the breaking release…

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by TorkelE** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by TorkelE** [comment]
@JuliaRegistrator register()

**Comment by TorkelE** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by vyudu** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register branch=release-15.0

Release notes:

This is a breaking release, please see the [HISTORY.md](https://github.com/SciML/Catalyst.jl/blob/master/HISTORY.md) file for details on breaking changes.

**Comment by isaacsas** [comment]
@JuliaRegistrator register branch=release-15.0.1

**Comment by isaacsas** [comment]
@JuliaRegistrator register branch=release-15.0.1

**Comment by isaacsas** [comment]
@JuliaRegistrator register branch=release-15.0.2

**Comment by isaacsas** [comment]
@JuliaRegistrator register branch=release-15.0.2

**Comment by isaacsas** [comment]
@JuliaRegistrator register branch=release-15.0.3

**Comment by isaacsas** [comment]
@JuliaRegistrator register branch=release-15.0.4

**Comment by isaacsas** [comment]
@JuliaRegistrator register branch=release-15.0.5

**Comment by isaacsas** [comment]
@JuliaRegistrator register branch=release-15.0.6

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by TorkelE** [comment]
@JuliaRegistrator register()

Release notes:
See HISTORY.md for breaking changes.

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

Release notes:
See HISTORY.md for breaking changes.

**Comment by TorkelE** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by isaacsas** [comment]
@JuliaRegistrator register()

**Comment by TorkelE** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()
