### ISSUE TITLE
Support for conserved quantities?

### ISSUE THREAD

**Issue by jlumpe** [SciML/Catalyst.jl#137]
It's common in a lot of biochemical network models to have an enzyme which transitions between an active and inactive form but otherwise exists in a fixed quantity. So you have

```julia
@reaction_network begin
(v1, v2), E_a <-> E_i
...
end
```

as the only reaction in which the amounts of `E_a` and `E_i` change. In this case you can take `E_t = E_a + E_i` to be a fixed parameter, and then you need only have `E_a` as a state variable because `E_i = E_t - E_a`.

Is this something you are planning to support?

**Comment by isaacsas** [comment]
In what way would you like this to be supported? The new steady-state and bifurcation methods by @TorkelE and @korsbo has added an `@add_constraint` macro that can be used to specify conservation laws. Currently it isn't hooked into any other types of solvers though, and we don't perform any analysis to discover such laws from the basic network.

**Comment by TorkelE** [comment]
I'd say it is both supported and not. Pardon my long text, but it is better to write to much to ensure I catch your question in the first try. Given the network
```julia
rn = @reaction_network begin
    (k1,k2), X ↔ Y
end
```
there exists a function
```julia
@add_constraint rn, X+Y=2
```
to record this information. However, this is only actually used for solving steady states. This function have also been recently added and the information is not used for anything else. It is possible that it can be used to speed-up ODE solvers. However, you can still solve the system using
```julia
prob = ODEProblem(rn,u0,tspan,p)
sol = solve(prob)
```
This will solve the system using for `X` and `Y` as state variables, and the result will be the same as if one reduce it. At some point it might be fun to include the rewriting, especially if we can get a decent speed-up from it. But given the non-urgent nature of the addition I am not sure when we'll get to it.

**Comment by isaacsas** [comment]
https://github.com/SciML/Catalyst.jl/pull/506
