### ISSUE TITLE
Proposed notation for delay

### ISSUE THREAD

**Issue by TorkelE** [SciML/Catalyst.jl#191]
I wouldn't look at the implementation of delay into DiffEqBio just yet.
(we will let MTK handle that, and first, we need jack DiffEqBio into MTK. I hope to start working on the DiffEqBio side of things in the next couple of day)

We could, however, start looking at how to allow time-delays to be given in the DiffEqBio DSL. I suggest using `[]` for this:
```julia
@reaction_network begin
    p, ∅ → X
    d*X[t-τ], X → ∅
end p d τ
```
here `X[t-τ]` would denote the value of the variable `X` at some previous time. I believe we have already reserved the value of `t` for the current time (cannot be used for other variables or parameters). `τ` would be a simple parameter to the model. One could also write a constant, such as `X[t-2.5]`. Allowing 
- Variables within `[]`,
- Bracket notation within the reactions,
- Time delays expressed in any other way that  `X[t-...]`,
probably would not make sense. We might also need some way to check that the `...` does not become negative. Or maybe we just let it become some error later on.

Does this sound reasonable?

**Comment by isaacsas** [comment]
Sounds reasonable to me, but I don't have much experience using the delay equation interface (so don't know how general it is or what we'd want to support). I guess once we see how it is done in MT we can have a similar level of support in the DSL here.

**Comment by korsbo** [comment]
Tricky. The mathematical notation uses round brackets. This gets a little bit confusing with Julia functions, but as long as he still know that X in your example is a variable then we should be good. Square brackets do not currently collide with anything in diffeqbio but what if we want to introduce spatial modelling? Square brackets would be natural for indexing.

**Comment by ChrisRackauckas** [comment]
Looks reasonable to me. Note that adding delay lowering in MTK for ODEs and DDEs is something on my mind but isn't the easiest thing in the world, but I plan to get to it in the next month. Delays in jumps will be an issue for a bit though, since we would need to change the jump interface to include the integrator so that it could grab the sol to interpolate the history.

**Comment by TorkelE** [comment]
Never thought about delays in Jumps.

Yes, it may take some time until this might actually come to use.

**Comment by TorkelE** [comment]
Given current development, I do not think this is the way to go. Something like
```julia
@reaction_network begin
    @delayed_variable Xτ ~ X(t-τ)
    p, ∅ --> X
    d*Xτ, X --> ∅
end
```
might be better though

**Comment by isaacsas** [comment]
`System` seems to just accept `X(t-\tau)` directly, so maybe we can just let people type that (and add a check to see if there are delayed variables / capture them).

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/ModelingToolkit.jl/pull/2208

**Comment by isaacsas** [comment]
Is it just constant lags currently?

**Comment by TorkelE** [comment]
> `System` seems to just accept `X(t-\tau)` directly, so maybe we can just let people type that (and add a check to see if there are delayed variables / capture them).

Exactly how would that look? E.g.
```julia
@reaction_network begin
    p, ∅ --> X
    d*X(t-τ), X --> ∅
end
```
and similar is problematic because currently `X(t-τ)` could be multiplication (rather than a function call with a delayed time).

**Comment by isaacsas** [comment]
How could it be multiplication? That valid in Julia is it?

**Comment by TorkelE** [comment]
No, you are right, I mixed it up!

**Comment by TorkelE** [comment]
Yes, your approach seems like the way to go
