### ISSUE TITLE
Enable noise scaling parameter in the chemical Langevin equation

### ISSUE THREAD

**Issue by TorkelE** [SciML/Catalyst.jl#201]
Short Summary: We should add a function `set_noise_scaling_parameter!(rn::ReactionSystem,η::Symbol)`, allowing one to set a noise calling parameter for the chemical Langevin equations of the system.

Previously it was possible to write
```julia
rn = @reaction_network rnType η begin
   (k1,k2), X ↔ Y
end p1 k2
```
which would extend the parameters by `η`, which would linearly scale the noise in the chemical Langevin equations:
*dX/dt = -k1\*X + k2\*Y - η\*sqrt(k1\*X)\*N1(0,1) + η\*sqrt(k2\*Y)\*N2(0,1)
dY/dt = k1\*X - k2\*Y + η\*sqrt(k1\*X)\*N1(0,1) - η\*sqrt(k2\*Y)\*N2(0,1)*
After the update, this is no longer possible.

One reason for not allowing this is that it's biologically incorrect. Only η=1, makes actual sense. However, I think there is one very good reason for still allowing η≠1; non-dimensionalisation. Say that we would want to reduce the number of parameters of the system to investigate its behaviour in a smaller parameter space.

In the deterministic case, we can simply divide both equations by k1, and rewrite T = k1*t and K = k2/k1.  But in the stochastic case this gives
*dX/dT = -X + K\*Y - sqrt(k1\*X)\*N1(0,1)/k1 + sqrt(k2\*Y)\*N2(0,1)/k1
dY/dT = X - K\*Y + sqrt(k1\*X)\*N1(0,1)/k1 - sqrt(k2\*Y)\*N2(0,1)/k1*
and here we actually have an η (= 1/k1).
(This is the well-known fact that the ration k2/k1 does not affect the deterministic case, but determines the level of noise in the stochastic one).

Here, doing non-dimensionalisation doesn't rid us of a parameter, but it still might be convenient to separate the parameters into one determining the system steady state, and one determining the noise (instead of having 2 both affecting both). In more complicated cases, permitting η≠1 could save the user having to write rather convoluted expressions when trying to reduce parameters.

The question is how to give this as an input. Previously we have added it at the beginning of the mode declaration `rn = @reaction_network rnType η begin ...`, other alternatives contemplated have been to add it as the last parameter `(... end p1 p2 p3 η`) or have it by default (and by default set to one). All these feels rather unnatural, it is plausible that we at some point would want to add more options when declaring the macro (I know I've said this for 2 years, and we haven't actually been close to adding anything). If we make declaring η possible as a part of `@reaction_network`, we should probably do so in a way which could also be used to declare other options. 

It could be done purely in MTK, when creating an `SDESystem` from a `ReactionSystem`. But one might want to have information that η is used in `ReactionSystem`, e.g. for the parameter list or when using Latexify.

For now, I think the easiest solution might be to create a function `set_noise_scaling_parameter!(rn::ReactionSystem,η::Symbol)`, which one can use for the purpose. Then we continue thinking on whenever this is information that actually should be possible to give to the macro, and if so, how.

As a side note, I think it would be nice to pass arguments for specific reactions, e.g. to have different noise scaling parameters for each reaction. Either we limit reaction specific options to when one manually builds `ReactionSystem`s using MTK functions, or we allow something like:
```julia
rn = @reaction_network rnType η begin
   (k1,k2), X ↔ Y, option1=:input1, option2=3 
   (k3,k4), Y ↔ Z, option2=4
end p1 k2
```
but I'm not sure when or if we would get there.

**Comment by ChrisRackauckas** [comment]
The Latexify recipes are in MTK, so that part wouldn't be an issue. Since this only applies to the CLE, I'm just curious why this wouldn't go in the ReactionSystem -> SDESystem conversion.

**Comment by TorkelE** [comment]
Good point. maybe so that it is reached when one call `parameters(::ReactionSystem)`? But I'm not sure if that's reason enough. Putting it in ReactionSystem -> SDESystem seems sensible.

**Comment by isaacsas** [comment]
Putting it in the `convert` call as a `kwarg` seems natural to me.

**Comment by isaacsas** [comment]
Closed by https://github.com/SciML/ModelingToolkit.jl/pull/530
