### ISSUE TITLE
Proper documentation

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/Catalyst.jl#209]
We should get a proper Documenter.jl documentation setup here

**Comment by isaacsas** [comment]
We should also add the doc analytics too. Working on CZI makes clear having such info would be good for funders...

**Comment by ChrisRackauckas** [comment]
Yes, we can add that. Though Julia v1.5 will give us download statistics through the package server which should be helpful.

**Comment by isaacsas** [comment]
Some revisions to make as we progress
1. Start with a simple example right up front. (SIR?)
2. List features right up front, including types of systems that can be solved, latex, network composition, flexibility in generated systems (sparse vs dense, serial vs threaded vs parallel), automatic DGs and partitioning of jumps, etc. 
3. Show some advanced features maybe (perhaps better in tutorials). e.g. building large networks incrementally, spatial or graph structures,  how to do bifurcations now (since we removed that functionality)...

**Comment by ChrisRackauckas** [comment]
I think there's a good style going that can be copied:

- Readme just has a quick piece of code and a picture that drives people to the docs.
- Index is a list of all of the features, making sure it's clear all of that stuff gets mentioned
- The docs opens with a sections that's a bunch of tutorials. They can be in the repo for now, but we're moving more and more over to DiffEqTutorials (soon SciMLTutorials) because its `!rebuild` mechanism keeps things up to date easily. We just need to make it possible to use those materials in other docs, which I hope we get someone working on soon.
- Then reference sections. This can include more than API docs.

The set of tutorials allows for explaining things which aren't necessarily just functionality of "the package". [DiffEqFlux.jl's docs](https://diffeqflux.sciml.ai/dev/) take that to the extreme, documenting how to fit all kinds of things, which most of those features just come for free by composition. I think the MTK and the DiffEq docs are probably the best looking, though the DiffEq docs are quite huge.

I can see Catalyst having a section of like 12 tutorials just from what we have right now.

**Comment by isaacsas** [comment]
Is there anything further I can do to help get the docs deployed? Going through the Documenter docs I think I could do most of the setup for a project github page, but there are some steps with keys/tokens that would require Travis account access for SciML I think.

**Comment by ChrisRackauckas** [comment]
you should have admin rights here

**Comment by isaacsas** [comment]
Do those carry over onto the Travis website? One needs to add a key into the account there I think.

**Comment by ChrisRackauckas** [comment]
that should give you privileges for the repo on the Travis site.

**Comment by isaacsas** [comment]
Awesome, I'll give it a try later and see then.

**Comment by isaacsas** [comment]
I took a first pass at splitting the monolithic doc we had previously into tutorials. We can now iterate to improve these and add more tutorials. Eventually some of these with lots of DSL syntax discussion can be switched to being ref docs, with more concise tutorials added in their place.

**Comment by isaacsas** [comment]
Closing since we've got docs now...
