### ISSUE TITLE
Latexify for arrays of chemical reactions

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/Catalyst.jl#210]
It would be nice to get a special one here for generating the chemical syntax. @korsbo did you have previous code for this?

**Comment by isaacsas** [comment]
https://github.com/SciML/Catalyst.jl/pull/225 gives use Latexify for `ReactionSystem`s. Going to individual `Reaction`s might be harder since we would lose the context / ordering that allows for reversible arrow notation.

**Comment by isaacsas** [comment]
Closed by https://github.com/SciML/Catalyst.jl/pull/225
