### ISSUE TITLE
ReactionSystem graph plotting / generation

### ISSUE THREAD

**Issue by isaacsas** [SciML/Catalyst.jl#216]
I like how Petri.jl does it visually (though I'd label the nodes with the actual species names, and maybe make the reaction nodes just small circles?).

**Comment by ChrisRackauckas** [comment]
I agree. This should come almost for free through LightGraphs integration? Might need to be  MetaGraph for the names.

**Comment by isaacsas** [comment]
It’ll be a bit of work to make it look good, but shouldn’t be too hard to do.

**Comment by isaacsas** [comment]
Closed by https://github.com/SciML/Catalyst.jl/pull/228
We can open new issues to discuss improvements or other types of reaction network graphs.
