### ISSUE TITLE
Move ReactionSystem definition over to Catalyst

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/Catalyst.jl#218]
I think in the mid run we should move the ReactionSystem definition over to Catalyst, since Catalyst's domain seems to be defined as all things around the `ReactionSystem`. However, for uniformity I want to leave it in there until @shashi finishes up a few things:

- [x] Term definition changes https://github.com/SciML/ModelingToolkit.jl/pull/518 
- [x] Aliases and inputs: https://github.com/SciML/ModelingToolkit.jl/issues/340
- [x] Make systems always store Operations: https://github.com/SciML/ModelingToolkit.jl/issues/433

**Comment by isaacsas** [comment]
With the last switch we’ll need to benchmark for performance regressions.
