### ISSUE TITLE
The first tutorial

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/Catalyst.jl#221]
The first tutorial is very important. About 90% of users will only know the functionality displayed in the first tutorial, so it's important that it gets to the core of the package. I think it needs to really hit some of the points home, like:

- Make a model, simulate the ODE
- Simulate the SDE and a quick explanation of the CLE
- Simulate the jump version 

all with pictures and some well-known model.

**Comment by isaacsas** [comment]
We can reuse the DiffEqTutorial example of the repressilator (and code).

**Comment by isaacsas** [comment]
Though if I remember right the CLE has issues with going negative on the repressilator.

**Comment by ChrisRackauckas** [comment]
I think it's alright if the first tutorial is just ODEs and jump processes, since that's kind of the core of these simulations. Showing a few nice ways to plot, calculate something cool, etc.

**Comment by isaacsas** [comment]
Closed by https://github.com/SciML/Catalyst.jl/pull/234
