### ISSUE TITLE
Tutorials to add

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/Catalyst.jl#222]
- [ ] Scaling to large reaction networks: handling parallelism and sparsity
- [ ] Choosing jump equation simulators
- [ ] File I/O and reading in reaction networks
- [ ] Getting back `Expr`s from the systems, saving models?
- [x] Modifying systems and using the API to build systems.
- [x] Time dependent rate and custom rate functions.
- [x] Parameter estimation on network models.

**Comment by isaacsas** [comment]
One thing we can really show over other packages is the ability to have a breadth of parameter estimation approaches using SciML tooling (maybe model component discovery too?). We should add tutorial(s) related to this (though I must admit that I'm not up on parameter estimation tooling, so I need to read up on this stuff).

**Comment by isaacsas** [comment]
We should add a set of tutorials for Julia "beginners", for whom using Catalyst is one of their first Julia uses (I think we get a decent number of such users). We could then split the tutorials into "Julia Beginner" tutorials and "Experience Julia User" tutorials.

**Comment by ChrisRackauckas** [comment]
Agreed, Catalyst will be the first package for many.

**Comment by TorkelE** [comment]
Maybe the following "beginner" tutorials:
- Introduction to using Catalyst (similar to what we have now).
- Simulating Catalyst models using DifferentialEquations.jl (basically a intro guide to DiffEq simulations and plotting).
- The reaction DSL (nothing there really requires additional Julia knowledge).
- Basica chemical reaction network examples (Might be interesting for people who are familiar with these CRNs, but not with Julia).
And the rest would go into the second set of tutorials.

**Comment by TorkelE** [comment]
I think in that case, it might be better to just split it, and have a separate "Catalyst & Julia for Julia beginners" tutorial, possibly in several sections. And then we let the current ones remain more or less like they are, but assuming basic Julia knowledge.

**Comment by isaacsas** [comment]
Closing as merged into https://github.com/SciML/Catalyst.jl/issues/515 to have one issue that tracks tutorials.
