### ISSUE TITLE
Add Graph tests

### ISSUE THREAD

**Issue by isaacsas** [SciML/Catalyst.jl#237]
I think we will also need a `Graph` call update for an API change on Catlab master soon as in:

https://github.com/mehalter/Petri.jl/pull/32/files

**Comment by isaacsas** [comment]
Test from https://github.com/SciML/Catalyst.jl/pull/242

Still need to update `Graph` syntax for after a new Catlab release is made.

**Comment by isaacsas** [comment]
Can't add tests due to needing a commandline Graphviz install.

**Comment by ChrisRackauckas** [comment]
Maybe @christopher-dG can look into building an artifact for that. Catlab.jl should really ship with the binary (@jpfairbanks)

**Comment by jpfairbanks** [comment]
I don’t know how to make that work, but given binary builder’s reputation it seems possible. What do we need to do to make it happen?

**Comment by ChrisRackauckas** [comment]
Someone who knows a bit of binary magic.

**Comment by isaacsas** [comment]
That would be great to have, and would help us both with CI.

**Comment by isaacsas** [comment]
If binary builder proves problematic, another option is it appears available through Anaconda. Maybe it can be pulled in using Conda.jl?

**Comment by ChrisRackauckas** [comment]
Conda is scary and leads to maintenance issues over time. I'd 100% try to avoid that if possible.

**Comment by christopher-dG** [comment]
I'll have a crack at building it with BB today. Looks straightforward unless there are some dependencies we don't yet have.

**Comment by jpfairbanks** [comment]
Awesome I’ll ping @ejpatters to make sure he is on the lookout for any Catlab PRs

**Comment by christopher-dG** [comment]
Wait... Graphviz_jll is already a thing. Have you guys tried that?

**Comment by ChrisRackauckas** [comment]
fastest binary building in the west!

**Comment by jpfairbanks** [comment]
It wasn’t working/sustainable at the time we adopted the current set up. Not sure if that has changed. I’d be happy to modernize that if necessary/feasible

**Comment by christopher-dG** [comment]
What was wrong with it?

**Comment by jpfairbanks** [comment]
We’ll have to wait for the west coast to wake up to ask Evan :)

**Comment by isaacsas** [comment]
@jpfairbanks Having not used jll's before I found this helpful:

https://github.com/JuliaBinaryWrappers/Graphviz_jll.jl

**Comment by isaacsas** [comment]
Maybe the issue is that Catlab wants to call more of the executables than are wrapped? It seems to want to call any of:
```
"dot","neato","fdp","sfdp","twopi","circo"
```
see 

https://github.com/AlgebraicJulia/Catlab.jl/blob/7c0313f011d6178433a76c05d64eb138da1330c9/src/graphics/Graphviz.jl#L121

**Comment by christopher-dG** [comment]
I just ran Graphviz's `build_tarballs.jl` manually and it does build all of those executables, they just aren't declared as products for the wrapper. I can update the build script to include all of those products.

**Comment by isaacsas** [comment]
Awesome, thanks for updating that! Hopefully with that change it will be a small tweak to the Catlab `open` call here

https://github.com/AlgebraicJulia/Catlab.jl/blob/7c0313f011d6178433a76c05d64eb138da1330c9/src/graphics/Graphviz.jl#L122

to get this working now.

**Comment by epatters** [comment]
So the history is: originally I used [GraphViz.jl](https://github.com/Keno/GraphViz.jl), which provides bindings to the Graphviz C API, but it became unmaintained and I couldn't [port it myself](https://github.com/Keno/GraphViz.jl/pull/32), so then I switched to just calling Graphviz through its CLI, assuming that the user had it installed.

Great to hear that somebody has built Graphviz using BinaryBuilder! Once it supplying all the right binaries we can definitely switch to that at Catlab.

**Comment by christopher-dG** [comment]
Nice, I'll get that PR up to Yggdrasil shortly.

**Comment by giordano** [comment]
> Looks straightforward

:joy: :joy: https://github.com/JuliaPackaging/Yggdrasil/pull/351 has been open for 5 months, look at the patches :joy:  And it doesn't even build for Windows because the entire Graphviz is completely messed up

**Comment by christopher-dG** [comment]
Yeah... I may have choked a bit when I saw the existing builder 😅

**Comment by isaacsas** [comment]
@christopher-dG @giordano Thanks for all your help with this! With the new jll setup this will fix our issues here.
