### ISSUE TITLE
Reaction rates as functions of time?

### ISSUE THREAD

**Issue by RajDandekar** [SciML/Catalyst.jl#238]
I understand that reaction rates can be defined as functions of other variables of the system. Can I define them as functions of time alone?

**Comment by ChrisRackauckas** [comment]
IIRC you just use `t` in there.

**Comment by isaacsas** [comment]
Here's a simple reaction with a Gaussian pulse in time for the production rate of a species and then linear degradation.
```julia
using Catalyst, DiffEqBase, OrdinaryDiffEq, Plots
rn = @reaction_network begin
           exp(-(t-5)^2), 0 --> S
           k, S --> 0
       end k
oprob = ODEProblem(rn, [0.0], (0.0,20.0), (1.0,))
sol = solve(oprob, Tsit5())
plot(sol)
```
giving
![pulse](https://user-images.githubusercontent.com/9385167/89235280-e6713180-d5bb-11ea-81ed-9d42f32441f8.png)

I'm going to close this, but feel free to post more if you have any further questions!

**Comment by ChrisRackauckas** [comment]
Do we have a doc example demonstrating this?

**Comment by isaacsas** [comment]
I'm not sure, but I was just thinking we should add one. I'll make a note in the tutorial TODO issue.

**Comment by TorkelE** [comment]
Don't think so. While they are perfectly possible, we don't really have much when it comes to t dependent rates. They are basically nonexistent in docs and tests. I think no one has really been using it much and it has become kinda forgotten.
