### ISSUE TITLE
Problems seem to require a parameter tuple/vector

### ISSUE THREAD

**Issue by isaacsas** [SciML/Catalyst.jl#239]
This gives an error:
```julia
using Catalyst, DiffEqBase, OrdinaryDiffEq
rn = @reaction_network begin
           exp(-(t-5)^2), 0 --> S
           1.0, S --> 0
       end 
oprob = ODEProblem(rn, [0.0], (0.0,20.0))
```
Seems we haven't setup the problem generation to allow for no parameters when skipping conversion from a system. (Probably we should fix this in MT, but I'm opening this here since it is a Catalyst issue and we might move ReactionSystems here eventually...)

**Comment by TorkelE** [comment]
Will have a look at this tomorrow, hopefully an easy fix.

**Comment by isaacsas** [comment]
Yeah, probably just need to default `p` to be a `DiffEqBase.NullParameters` and then avoid parameters calculations in that case.

**Comment by isaacsas** [comment]
Closed by https://github.com/SciML/ModelingToolkit.jl/pull/542
