### ISSUE TITLE
Latexify failures look fake?

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/Catalyst.jl#254]
Downstream is all fixed up so the tests basically pass again, but Latexify tests fail and I can't figure out why. They look... correct. I think it might be off by a white space or something, but even the tests when regenerating with via `Latexify.@generate_test` are failing, so I'm a bit confused. 

@korsbo

**Comment by korsbo** [comment]
I have had a similar issue before. Tests worked fine when I created them on a Unix machine but not if they were created on windows. I'm guessing that it's about the end-of-line character or some other platform-specific quirk of strings.

**Comment by isaacsas** [comment]
Tests disabled for now, we can fix later once we figure out a more robust way to handle these issues across OSes:
see https://github.com/SciML/Catalyst.jl/pull/257

**Comment by isaacsas** [comment]
Closed by https://github.com/SciML/Catalyst.jl/pull/285
