### ISSUE TITLE
Obtaining first order derivatives from the odesystem of Catalyst ?

### ISSUE THREAD

**Issue by yewalenikhil65** [SciML/Catalyst.jl#256]
Hello,
This is really cool package for chem-kinetics. I wonder if there is way to create ideal-derivative (first order) from the **@reaction_network itself** as we do by plugging into the function as shown below

`
function lorenz(u,p,t)
    x, y, z = u
    ẋ = 10.0*(y - x)
    ẏ = x*(28.0-z) - y
    ż = x*y - (8/3)*z
    return [ẋ, ẏ, ż]
end
#solving ODE system using solve.. skipping this part

X = Array(solution)
DX = similar(X)                     # ideal-derivative from the model itself
**for (i, xi) in enumerate(eachcol(X))
    DX[:,i] = lorenz(xi, [], 0.0)
end**`

**Comment by isaacsas** [comment]
Is this what you mean?
```julia
using Catalyst
rn = @reaction_network begin
    α, S + I --> 2I
    β, I --> R
end α β

using DiffEqBase, OrdinaryDiffEq
p     = [.1/1000, .01]           # [α,β]
tspan = (0.0,250.0)
u0    = [999.0,1.0,0.0]          # [S,I,R] at t=0
op    = ODEProblem(rn, u0, tspan, p)
du = copy(u0)
op.f(du,u0,p,0.0)
```
`du` now stores `[dS/dt,dI/dt,dR/dt]` at `t=0`.

**Comment by yewalenikhil65** [comment]
I wished to get `[dS/dt,dI/dt,dR/dt]` at function of time(0.0, 250.0) from this model itself (without resorting to Numerical differentiation or Autodiff )
Also, can you please let me know what `op.f(du,u0,p,0.0)` does ?

**Comment by ChrisRackauckas** [comment]
It evaluates the RHS of the ODE.

**Comment by isaacsas** [comment]
To add, if `u = [S,I,R]` at time `t` then 
```julia
op.f(du,u,p,t)
```
fills the vector `du` with the derivatives `[dS/dt(t),dI/dt(t),dR/dt(t)]` which you want.

**Comment by isaacsas** [comment]
`op.f` corresponds to an in-place version of your `lorenz` function for the SIR model, and is generated automatically when you call `ODEProblem`.

**Comment by yewalenikhil65** [comment]
Ok, thank you , sir!
I hope this means, here DX contains information of `[dS/dt,dI/dt,dR/dt]` with time

```
sol = solve(op, QNDF(),saveat=2)
t = 0.0:2.0:250.0;
X = Array(sol)    # solution array
DX = similar(X)  # derivative of solution array  ??
for i in 1:length(t)
       op.f(du, X[:,i], p,t[i])
       DX[:,i] =  du
end
```

**Comment by isaacsas** [comment]
It should! If we've answered your question could you close this issue? (But feel free to open another if you have further problems!)

**Comment by yewalenikhil65** [comment]
Yup, closing..
Thanks for help! :)
