### ISSUE TITLE
Obtaining substrate and product stoichiometric matrices from Catalyst reaction network 

### ISSUE THREAD

**Issue by yewalenikhil65** [SciML/Catalyst.jl#261]
Hello,
Can anyone direct me on how to automatically obtain substrate and product stoichiometric matrices from a reaction network defined using @reaction_network using ?

**Comment by isaacsas** [comment]
We don't have a function to generate these currently, but should definitely add one. For now you can build them yourself using the `substoich` and `prodstoich` fields of each reaction:
```julia
rn = @reaction_network begin
           α, S + I --> 2I
           β, I --> R
       end α β
for rx in reactions(rn)
    println("substrates are: $(rx.substrates), their stoich is $(rx.substoich)")
    println("products are: $(rx.products), their stoich is $(rx.prodstoich)")
end
```
You can get the integer id of species within a given reaction as follows:
```julia
rx = reactions(rn)[1]
sm = speciesmap(rn)
for sub in rx.substrates
   println("species $(sub) has id $(sm[sub.op])")
end
```

**Comment by yewalenikhil65** [comment]
Thank you ! This code works perfectly as expected

**Comment by isaacsas** [comment]
I was actually cleaning this up for you. Here is a version that actually makes the matrices:
```julia
rn = @reaction_network begin
           α, S + I --> 2I
           β, I --> R
       end α β

smat = zeros(Int,(numreactions(rn),numspecies(rn)))
smap = speciesmap(rn)
for (k,rx) in enumerate(reactions(rn))
	stoich = rx.substoich
	for (i,sub) in enumerate(rx.substrates)
		smat[k,smap[sub.op]] = stoich[i]
	end
end

pmat = zeros(Int,size(smat))
for (k,rx) in enumerate(reactions(rn))
	stoich = rx.prodstoich
	for (i,prod) in enumerate(rx.products)
		pmat[k,smap[prod.op]] = stoich[i]
	end
end
```
Please double check this though, as I haven't extensively tested it (only used on this one example).

**Comment by yewalenikhil65** [comment]
Hello @isaacsas 
This works perfect . I have checked on three more examples :) 
I will definitely let you know if anything inconsistent comes up.

**Comment by isaacsas** [comment]
Great. I'll plan to put in a PR when I have a chance adding this to the API. Thanks for asking about it!

**Comment by isaacsas** [comment]
Closed by https://github.com/SciML/Catalyst.jl/pull/273
