### ISSUE TITLE
Remove evals for RuntimeGeneratedFunctions.jl

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/Catalyst.jl#262]
When https://github.com/SciML/ModelingToolkit.jl/pull/595 is done we will know the library is ready, in which case we should replace the evals.

**Comment by isaacsas** [comment]
Which `eval`s are you referring too? I don’t see any on a quick search through the repo.

**Comment by ChrisRackauckas** [comment]
Oh oops, the search was picking up an old script. Yeah master is good to go since it's all in MTK
