### ISSUE TITLE
visualization graph is not displayed

### ISSUE THREAD

**Issue by danielchen26** [SciML/Catalyst.jl#266]
`using Catalyst
rn = @reaction_network begin
    α, S + I --> 2I
    β, I --> R
end α β
using Catlab.Graphics.Graphviz Graph(rn)`
gives error
`ERROR: MethodError: no method matching Graph(::ReactionSystem)
Closest candidates are:
  Graph(::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any) at /Users/chentianchi/.julia/packages/Parameters/CVyBv/src/Parameters.jl:480
  Graph(; name, directed, prog, stmts, graph_attrs, node_attrs, edge_attrs) at /Users/chentianchi/.julia/packages/Parameters/CVyBv/src/Parameters.jl:468
  Graph(::Graph; kws...) at /Users/chentianchi/.julia/packages/Parameters/CVyBv/src/Parameters.jl:530
  ...
Stacktrace:
 [1] top-level scope at REPL[21]:1`

**Comment by isaacsas** [comment]
For some reason currently updating Catlab to 0.9 downgrades Catalyst to 5.0.1. A temp fix is to downgrade Catlab to 0.8.2 and then you can update Catalyst to 5.1.

Thanks for catching this!

**Comment by ChrisRackauckas** [comment]
Can you paste the resolver output from forcing `]add Catlab 0.9`?

**Comment by danielchen26** [comment]
(@v1.5) pkg> up Catalyst
   Updating registry at `~/.julia/registries/General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Installed ArrayInterface ─── v2.13.5
  Installed CanonicalTraits ── v0.2.3
  Installed OffsetArrays ───── v1.3.1
  Installed JLD2 ───────────── v0.2.4
  Installed Bijectors ──────── v0.8.7
  Installed JLLWrappers ────── v1.1.1
  Installed ImageCore ──────── v0.8.18
  Installed MCMCChains ─────── v4.2.3
  Installed Compat ─────────── v3.20.0
  Installed Libtask ────────── v0.4.2
  Installed ChainRulesCore ─── v0.9.14
  Installed DynamicPPL ─────── v0.9.6
  Installed NearestNeighbors ─ v0.4.7
  Installed ZipFile ────────── v0.9.3
  Installed Catalyst ───────── v5.1.0
Updating `~/.julia/environments/v1.5/Project.toml`
  [479239e8] ↑ Catalyst v5.0.1 ⇒ v5.1.0
Updating `~/.julia/environments/v1.5/Manifest.toml`
  [4fba245c] ↑ ArrayInterface v2.13.3 ⇒ v2.13.5
  [76274a88] ↑ Bijectors v0.8.6 ⇒ v0.8.7
  [a603d957] ↑ CanonicalTraits v0.2.2 ⇒ v0.2.3
  [479239e8] ↑ Catalyst v5.0.1 ⇒ v5.1.0
  [d360d2e6] ↑ ChainRulesCore v0.9.13 ⇒ v0.9.14
  [34da2185] ↑ Compat v3.19.0 ⇒ v3.20.0
  [366bfd00] ↑ DynamicPPL v0.9.4 ⇒ v0.9.6
  [a09fc81d] ↑ ImageCore v0.8.17 ⇒ v0.8.18
  [033835bb] ↑ JLD2 v0.2.3 ⇒ v0.2.4
  [692b3bcd] ↑ JLLWrappers v1.1.0 ⇒ v1.1.1
  [6f1fad26] ↑ Libtask v0.4.1 ⇒ v0.4.2
  [c7f686f2] ↑ MCMCChains v4.2.2 ⇒ v4.2.3
  [b8a86587] ↑ NearestNeighbors v0.4.6 ⇒ v0.4.7
  [6fe1bfb0] ↑ OffsetArrays v1.3.0 ⇒ v1.3.1
  [a5390f91] ↑ ZipFile v0.9.2 ⇒ v0.9.3
   Building Libtask → `~/.julia/packages/Libtask/OtgFl/deps/build.log`

**Comment by ChrisRackauckas** [comment]
]add Catlab 0.9?

**Comment by isaacsas** [comment]
```julia
(@v1.5) pkg> add Catlab@0.9
  Resolving package versions...
  Installed Catlab ─ v0.9.0
Updating st
`~/.julia/environments/v1.5/Project.toml`
  [479239e8] ↓ Catalyst v5.1.0 ⇒ v5.0.1
  [134e5e36] ↑ Catlab v0.8.2 ⇒ v0.9.0
  [a077e3f3] ↓ DiffEqProblemLibrary v4.9.1 ⇒ v4.8.1
  [b4db0fb7] ↓ ReactionNetworkImporters v0.2.0 ⇒ v0.1.5
Updating `~/.julia/environments/v1.5/Manifest.toml`
  [479239e8] ↓ Catalyst v5.1.0 ⇒ v5.0.1
  [134e5e36] ↑ Catlab v0.8.2 ⇒ v0.9.0
  [a077e3f3] ↓ DiffEqProblemLibrary v4.9.1 ⇒ v4.8.1
  [b4db0fb7] ↓ ReactionNetworkImporters v0.2.0 ⇒ v0.1.5
```
That's what I got why I had Catalyst 5.1 and updated Catlab.

**Comment by danielchen26** [comment]
(@v1.5) pkg> add Catlab@0.9
  Resolving package versions...
  Installed DiffEqParamEstim ─ v1.18.1
  Installed StatsPlots ─────── v0.14.14
  Installed DataFrames ─────── v0.21.8
  Installed Turing ─────────── v0.14.10
  Installed AbstractPlotting ─ v0.12.15
Updating `~/.julia/environments/v1.5/Project.toml`
  [537997a7] ↑ AbstractPlotting v0.12.14 ⇒ v0.12.15
  [479239e8] ↓ Catalyst v5.1.0 ⇒ v5.0.1
  [134e5e36] ↑ Catlab v0.8.2 ⇒ v0.9.0
  [a93c6f00] ↑ DataFrames v0.21.7 ⇒ v0.21.8
  [1130ab10] ↑ DiffEqParamEstim v1.18.0 ⇒ v1.18.1
  [f3b207a7] ↑ StatsPlots v0.14.13 ⇒ v0.14.14
  [fce5fe82] ↑ Turing v0.14.7 ⇒ v0.14.10
Updating `~/.julia/environments/v1.5/Manifest.toml`
  [537997a7] ↑ AbstractPlotting v0.12.14 ⇒ v0.12.15
  [479239e8] ↓ Catalyst v5.1.0 ⇒ v5.0.1
  [134e5e36] ↑ Catlab v0.8.2 ⇒ v0.9.0
  [a93c6f00] ↑ DataFrames v0.21.7 ⇒ v0.21.8
  [1130ab10] ↑ DiffEqParamEstim v1.18.0 ⇒ v1.18.1
  [f3b207a7] ↑ StatsPlots v0.14.13 ⇒ v0.14.14
  [fce5fe82] ↑ Turing v0.14.7 ⇒ v0.14.10

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
It was just missing a tag.

**Comment by isaacsas** [comment]
Doh! Thanks!

**Comment by danielchen26** [comment]
Thanks!
