### ISSUE TITLE
Error in using reaction rates as function of species

### ISSUE THREAD

**Issue by yewalenikhil65** [SciML/Catalyst.jl#276]
Following code generates an error when dealing with reaction rates as a function of species

```julia
using Catalyst

@reaction_func k2(x) = 0.5*( sign(x - 0.5) + 1 ) # reaction rate k2 as heaviside function/step function to activate reaction only when concentration of A exceeds certain threshold
rn =@reaction_network begin
      k1, A --> B
      k2(A) , B --> X
end k1  # edited, removed k2 from here.. but still same error

>>TypeError: non-boolean (Operation) used in boolean context
```
However, if I simply erase `sign` keyword , this seems to work(although not the rate k2 as intended). There seems some issue with the `sign` function usage with `@reaction_func` macro.

Other functions such as `abs` also seems to work perfectly.
(If this is not the correct way of representing rate k2 as heaviside function in Catalyst, please let me know the correct way.)

**Comment by TorkelE** [comment]
You have declared k2 as a parameter
```
end k1 k2
```
I am not sure, but this likely not a good thing to do when trying to sue it as a function.

**Comment by yewalenikhil65** [comment]
> You have declared k2 as a parameter
> 
> ```
> end k1 k2
> ```
Even if I erase k2 at the `end` line, it still throws the same error.  I feel its particularly with functions similar to `sign` function

**Comment by TorkelE** [comment]
Yeah, you are right. The `sign` function seems to not work. Even more minimal examples
```
@reaction_network begin
      sign(X), X --> 0
end 
```
```julia
@reaction_network begin
      sign(k1), X --> 0
end k1
```

This works though
```
@reaction_network begin
      sign(1.0), X --> 0
end k1
```

Not sure what is going on to be honest. In the meantime you might be able to write a similar function but without using `sign`. This should hold `sign(x)=x/abs(x)`?

**Comment by yewalenikhil65** [comment]
Yea, This definition x/abs(x) should work, but have to pray that `x !=0` or in my case `x !=` whatever threshold I am considering, since i am really looking for function like `sign(x - some_threshold)`. Or else if will simply calculate rate as NaN or Inf

Trouble seems to arise due to `if else` kind of boolean operations used in definition of `sign` function not being compatible with `@reaction_func` macro defined functions ?

**Comment by TorkelE** [comment]
`@reaction_func` is not involved, see my examples above. 

An alternative you could use is arctan, the function `x -> 2*atan(k*x)/pi` -> `sign` as `k`->`inf`. Just select a sufficiently large k. This will also make the function continuous, which might be a useful thing (a trick @ChrisRackauckas showed me a few years ago).

**Comment by yewalenikhil65** [comment]
> `@reaction_func` is not involved, see my examples above.
> 
> An alternative you could use is arctan, the function `x -> 2*atan(k*x)/pi` -> `sign` as `k`->`inf`. Just select a sufficiently large k. This will also make the function continuous, which might be a useful thing (a trick @ChrisRackauckas showed me a few years ago).

Thanks @TorkelE 
You are absolutely right. For now, I will try this workaround. Meanwhile `sign` is also nearly same as `x/ sqrt(x^2 +  ε^2 )`. If I choose  ε ->0, I should recover similar behavior of `sign` function

**Comment by isaacsas** [comment]
Registering the function with ModelingToolkit first seems to get past the given error (but I haven't checked it gives correct results further down the line):
```julia
using Catalyst
@register Base.sign(x)
@reaction_func k2(x) = 0.5*( sign(x - 0.5) + 1 )
rn =@reaction_network begin
      k1, A --> B
      k2(A) , B --> X
end k1 
```

**Comment by isaacsas** [comment]
I think it is giving the correct ODEs too:
```julia
julia> osys = convert(ODESystem,rn)
ODESystem(Equation[Equation(Differential(A(t)), -(k1 * A(t))), Equation(Differential(B(t)), (k1 * A(t)) - ((0.5 * (sign(A(t) - 0.5) + 1)) * B(t))), Equation(Differential(X(t)), (0.5 * (sign(A(t) - 0.5) + 1)) * B(t))], t, Term{Real}[A(t), B(t), X(t)], Sym{ModelingToolkit.Parameter{Real}}[k1], Num[], Equation[], Base.RefValue{Array{Num,1}}(Num[]), Base.RefValue{Any}(Array{Num}(undef,0,0)), Base.RefValue{Array{Num,2}}(Array{Num}(undef,0,0)), Base.RefValue{Array{Num,2}}(Array{Num}(undef,0,0)), Symbol("##ReactionSystem#253"), ODESystem[])

julia> equations(osys)
3-element Array{Equation,1}:
 Equation(Differential(A(t)), -(k1 * A(t)))
 Equation(Differential(B(t)), (k1 * A(t)) - ((0.5 * (sign(A(t) - 0.5) + 1)) * B(t)))
 Equation(Differential(X(t)), (0.5 * (sign(A(t) - 0.5) + 1)) * B(t))
```

**Comment by isaacsas** [comment]
@TorkelE I wonder if there is a way we can drop `reaction_func` and just pass rates through to ModelingToolkit. That might help with https://github.com/SciML/Catalyst.jl/issues/248 too.

**Comment by TorkelE** [comment]
It seems like MTK and `reaction_func` interact weirdly under some circumstances, so might be sensible. Especially if a solution using MTK would be beneficial for other uses of MTK.

**Comment by isaacsas** [comment]
Closed by https://github.com/SciML/Catalyst.jl/pull/286

Let's make a new issue if followup testing shows conversion isn't working from the generated `ReactionSystem`.
