### ISSUE TITLE
Custom Function (`@reaction_func`) is not documentable

### ISSUE THREAD

**Issue by stevengogogo** [SciML/Catalyst.jl#278]
Dear Developer,

I'm using this module for building cell systems. Recently, I found that the docstring is not compatible with the `@reaction_func` macro, and even reports error when `"""..."""` is above the interpretation. If possible, I hope `  @reaction_func` can be documentable.

Here is the error I encountered when using docstring for the `@reaction_func`: 

## Error

```julia-repl
julia> using Catalyst
julia> """
           MM(chem, k, kd) 

       Michaelis Menten Equation

       Reference
       ---------
       1. Michaelis Menten. Wikipidia.
       """
       @reaction_func MM(chem, k, kd)= k* chem / (kd + chem)
ERROR: cannot document the following expression:

#= REPL[26]:10 =# @reaction_func MM(chem, k, kd) = begin
            #= REPL[26]:10 =#
            (k * chem) / (kd + chem)
        end

'@reaction_func' not documentable. See 'Base.@__doc__' docs for details.

Stacktrace:
 [1] error(::String, ::String) at ./error.jl:42
 [2] top-level scope at REPL[26]:1
```

## Version

```sh
  [479239e8] Catalyst v6.0.0
```

**Comment by ChrisRackauckas** [comment]
`@reaction_func` isn't a function, it's a macro. That said, `@reaction_func` is being removed in place of the more general MTK registration system, so this issue should be fixed at the same time.

**Comment by stevengogogo** [comment]
Thank you! 

Just wondering that if there is a way to test the behavior of the custom method in MTK registration system? Or execute the registered function in MTK environment.

**Comment by ChrisRackauckas** [comment]
Not yet. The implementation needs to happen first.
