### ISSUE TITLE
Enable "<-->" for two way reactions

### ISSUE THREAD

**Issue by TorkelE** [SciML/Catalyst.jl#287]
Currently not possible since Julia interpret `:(<-->)` as a `<` followed by a `-->` (a function from a `<` to something). If it would somehow become possible to use the expression `:(<-->)`, this should be fixed though. Not sure whenever this is a plausible (or even possible) thing to hope for. I believe there was a discussion on Julia about this? If so, I cannot find it.

**Comment by isaacsas** [comment]
Should be in 1.6
https://github.com/JuliaLang/julia/blob/release-1.6/NEWS.md

**Comment by TorkelE** [comment]
Did my tests on 1.5, so this is good news! I will implement <-- and <--> in the coming week.

**Comment by TorkelE** [comment]
OK, haven#t been keeping up to date on the releases. Got confused and though 1.6 had been released already, that does not seem to be the case. Will get to it when 1.6 is ready.

**Comment by isaacsas** [comment]
Yeah, no point working on this till 1.6 is out since no one will be able to use it. We can make a breaking release once 1.6 is out that requires 1.6 so we don't have to worry about handling earlier Julia versions too.

**Comment by isaacsas** [comment]
Closed by https://github.com/SciML/Catalyst.jl/pull/322
