### ISSUE TITLE
Feature request for Representing reactions with focus on intermediate complexes

### ISSUE THREAD

**Issue by yewalenikhil65** [SciML/Catalyst.jl#318]
I think it would be nice to introduce another representation of chemical reactions in `Catalyst` which represents network with a focus on  intermediate complexes.. Such way is very useful in modelling reduced order methods. 

This shall enable in calculating certain `incidence matrices` of reaction graph, `Laplacian matrices` etc..This also helps in writing ODESystem in another alternate form that involves these matrices

On similar lines, it would be nice to visualize network with `Graph(rn)` representing  intermediate complexes as nodes (naturally stoichometry is also taken care in the nodes) and edges as reaction arrows. It could be less messy for bigger reaction networks to visualize that way.

**Comment by isaacsas** [comment]
If you want to add new graph visualization options and/or a new system type with all the conversions it needs and such go ahead! PRs are welcome. I’d like to get a system type in, perhaps `StoichMatSystem`, that is the representation we’ve previously discussed, but right now I don’t have time to work on it. In ~ month classes should end, and I can circle back to this if no one else has picked it up.

**Comment by yewalenikhil65** [comment]
> If you want to add new graph visualization options and/or a new system type with all the conversions it needs and such go ahead! PRs are welcome. I’d like to get a system type in, perhaps `StoichMatSystem`, that is the representation we’ve previously discussed, but right now I don’t have time to work on it. In ~ a month classes should end, and I can circle back to this if no one else has picked it up.

I will like to try on following basis when i begin.. noting here for future purpose
"A network dynamics approach to chemicalreaction networks" https://arxiv.org/pdf/1502.02247.pdf

**Comment by yewalenikhil65** [comment]
@isaacsas , I would to know your thoughts on https://github.com/yewalenikhil65/Catalyst.jl/discussions/2
whenever you are free.. Its based on what i said in https://github.com/SciML/Catalyst.jl/issues/318#issue-838413865

**Comment by yewalenikhil65** [comment]
clsoed with https://github.com/SciML/Catalyst.jl/pull/373
