### ISSUE TITLE
Error while running script from documentation

### ISSUE THREAD

**Issue by bosonbaas** [SciML/Catalyst.jl#350]
While running the code included in the documentation on ["Generating ReactionSystems Programmatically"](https://catalyst.sciml.ai/stable/tutorials/generating_reactions_programmatically/), I ran into an error at the line
```julia
rs = ReactionSystem(rx, t, X, k)
```

The full error output is:
```
ERROR: LoadError: MethodError: no method matching CartesianIndices(::Tuple{Vector{Int64}})
Closest candidates are:
  (::Type{T})(::Num) where T<:Union{Number, AbstractArray} at /Users/user/.julia/packages/Symbolics/aomWY/src/num.jl:8
  CartesianIndices(::Tuple{}) at multidimensional.jl:269
  CartesianIndices(::R) where {N, R<:Tuple{Vararg{OrdinalRange{Int64, Int64}, N}}} at multidimensional.jl:266
  ...
Stacktrace:
 [1] eachindex(A::Symbolics.Arr{Any, 1})
   @ Symbolics ~/.julia/packages/Symbolics/aomWY/src/arrays.jl:464
 [2] iterate(A::Symbolics.Arr{Any, 1})
   @ Base ./abstractarray.jl:1094
 [3] check_variables(dvs::Symbolics.Arr{Any, 1}, iv::Sym{Real, Base.ImmutableDict{DataType, Any}})
   @ ModelingToolkit ~/.julia/packages/ModelingToolkit/VigaA/src/utils.jl:115
 [4] ReactionSystem(eqs::Vector{Any}, iv::Num, states::Symbolics.Arr{Num, 1}, ps::Symbolics.Arr{Num, 1}, observed::Vector{Any}, name::Symbol, systems::Vector{Any}, defaults::Dict{Any, Any})
   @ ModelingToolkit ~/.julia/packages/ModelingToolkit/VigaA/src/systems/reaction/reactionsystem.jl:162
 [5] #ReactionSystem#395
   @ ~/.julia/packages/ModelingToolkit/VigaA/src/systems/reaction/reactionsystem.jl:177 [inlined]
 [6] ReactionSystem(eqs::Vector{Any}, iv::Num, species::Symbolics.Arr{Num, 1}, params::Symbolics.Arr{Num, 1})
   @ ModelingToolkit ~/.julia/packages/ModelingToolkit/VigaA/src/systems/reaction/reactionsystem.jl:177
 [7] top-level scope
   @ ~/Documents/catalyst_test/docs_test.jl:66
in expression starting at /Users/user/Documents/catalyst_test/docs_test.jl:66
```
The versions of each of the packages in this environment are as follows:

```
(catalyst_test) pkg> status
      Status `~/Documents/catalyst_test/Project.toml`
  [479239e8] Catalyst v6.14.0
  [2b5f629d] DiffEqBase v6.68.1
  [c894b116] DiffEqJump v6.15.1
  [961ee093] ModelingToolkit v5.25.0
  [91a5bcdd] Plots v1.19.3
  [276daf66] SpecialFunctions v1.5.1
  [37e2e46d] LinearAlgebra
```

This error appears to be resolved if I instead run:
```julia
rs = ReactionSystem(rx, t, collect(X),collect(k))
```
yet this changes the normal nicely formatted chemical equation output to
```
Model ##ReactionSystem#268 with 25 equations
States (10):
  X[1](t)
  X[2](t)
  X[3](t)
  X[4](t)
  X[5](t)
  X[6](t)
⋮
Parameters (25):
  k[1]
  k[2]
  k[3]
  k[4]
  k[5]
  k[6]
⋮
```

I have been able to successfully run this section of the documentation with previous versions, so would appreciate any pointers if there's something I'm doing incorrectly, thanks!

**Comment by yewalenikhil65** [comment]
Hi @bosonbaas , what version of Catalyst you were using when you ran into the error ?

**Comment by yewalenikhil65** [comment]
> Hi @bosonbaas , what version of Catalyst you were using when you ran into the error ?

right 6.14.0.. taking a look now.. will get back quick

**Comment by yewalenikhil65** [comment]
@bosonbaas , can you try with these lines.. and rest all same  as docs
```julia
@variables k[1:nr]  X[1:N](t)

rs = ReactionSystem(rx, t, X, k)
```

**Comment by bosonbaas** [comment]
Certainly! I replaced the
```julia
@variables k[1:nr]  X[collect(1:N)](t)
```
with
```julia
@variables k[1:nr]  X[1:N](t)
```
I get different error now, given below:
```
ERROR: LoadError: ArgumentError: Variable (broadcast(value, map(Symbolics.CallWith((t,)), X)))[1] is not a function of independent variable t.
Stacktrace:
 [1] check_variables(dvs::Symbolics.Arr{Any, 1}, iv::Sym{Real, Base.ImmutableDict{DataType, Any}})
   @ ModelingToolkit ~/.julia/packages/ModelingToolkit/VigaA/src/utils.jl:117
 [2] ReactionSystem(eqs::Vector{Any}, iv::Num, states::Symbolics.Arr{Num, 1}, ps::Symbolics.Arr{Num, 1}, observed::Vector{Any}, name::Symbol, systems::Vector{Any}, defaults::Dict{Any, Any})
   @ ModelingToolkit ~/.julia/packages/ModelingToolkit/VigaA/src/systems/reaction/reactionsystem.jl:162
 [3] #ReactionSystem#395
   @ ~/.julia/packages/ModelingToolkit/VigaA/src/systems/reaction/reactionsystem.jl:177 [inlined]
 [4] ReactionSystem(eqs::Vector{Any}, iv::Num, species::Symbolics.Arr{Num, 1}, params::Symbolics.Arr{Num, 1})
   @ ModelingToolkit ~/.julia/packages/ModelingToolkit/VigaA/src/systems/reaction/reactionsystem.jl:177
 [5] top-level scope
   @ ~/Documents/catalyst_test/docs_test.jl:66
in expression starting at /Users/user/Documents/catalyst_test/docs_test.jl:66
```

**Comment by yewalenikhil65** [comment]
I am unable to update to newer Catalyst for some reason.  
@isaacsas any idea why this would happen ? Another tutorial i am submitting for PR https://github.com/SciML/Catalyst.jl/pull/326 is also based on similar idea as that this issue.

**Comment by bosonbaas** [comment]
This issue might be related to PR https://github.com/SciML/Catalyst.jl/pull/341. When I force Symbolics.jl to `v0.1.32` instead of `v1.4.1`, the documentation script works (this also changes Catalyst.jl to `v6.13.0`)
```
(catalyst_test) pkg> status
      Status `~/Documents/catalyst_test/Project.toml`
  [479239e8] Catalyst v6.13.0
  [2b5f629d] DiffEqBase v6.68.1
  [c894b116] DiffEqJump v6.15.1
  [961ee093] ModelingToolkit v5.20.0
  [91a5bcdd] Plots v1.19.3
  [276daf66] SpecialFunctions v1.5.1
  [0c5d862f] Symbolics v0.1.32
  [37e2e46d] LinearAlgebra
```

**Comment by isaacsas** [comment]
I think using `collect` is the right thing to do here. This is the result of the change of ModelingToolkit and Symbolics.jl to support array variables.

@YingboMa is there a way to nicely print array variables with subscripts for indices?

**Comment by isaacsas** [comment]
@bosonbaas everything works when using `collect` right, it just doesn't print as nicely?

**Comment by bosonbaas** [comment]
When I insert `collect`, it runs until this line:
```julia
dprob   = DiscreteProblem(jumpsys, u₀map, tspan, pars)
```

That results in this error:
```
ERROR: LoadError: MethodError: no method matching CartesianIndices(::Tuple{Vector{Int64}})
Closest candidates are:
  CartesianIndices(::Tuple{}) at multidimensional.jl:269
  CartesianIndices(::R) where {N, R<:Tuple{Vararg{OrdinalRange{Int64, Int64}, N}}} at multidimensional.jl:266
  CartesianIndices(::Tuple{Vararg{OrdinalRange{var"#s832", var"#s831"} where {var"#s832"<:Integer, var"#s831"<:Integer}, N}}) where N at multidimensional.jl:270
  ...
Stacktrace:
 [1] eachindex(A::Symbolics.Arr{Any, 1})
   @ Symbolics ~/.julia/packages/Symbolics/S525E/src/arrays.jl:463
 [2] iterate(A::Symbolics.Arr{Any, 1})
   @ Base ./abstractarray.jl:1094
 [3] varmap_to_vars(varmap::Symbolics.Arr{Any, 1}, varlist::Vector{Term{Real, Nothing}}; defaults::Dict{Any, Any}, check::Bool, toterm::Function)
   @ ModelingToolkit ~/.julia/packages/ModelingToolkit/YwkDi/src/variables.jl:48
 [4] DiscreteProblem(sys::JumpSystem{RecursiveArrayTools.ArrayPartition{Any, Tuple{Vector{MassActionJump}, Vector{ConstantRateJump}, Vector{VariableRateJump}}}}, u0map::Symbolics.Arr{Any, 1}, tspan::Tuple{Float64, Float64}, parammap::Symbolics.Arr{Any, 1}; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ ModelingToolkit ~/.julia/packages/ModelingToolkit/YwkDi/src/systems/jumps/jumpsystem.jl:225
 [5] DiscreteProblem(sys::JumpSystem{RecursiveArrayTools.ArrayPartition{Any, Tuple{Vector{MassActionJump}, Vector{ConstantRateJump}, Vector{VariableRateJump}}}}, u0map::Symbolics.Arr{Any, 1}, tspan::Tuple{Float64, Float64}, parammap::Symbolics.Arr{Any, 1})
   @ ModelingToolkit ~/.julia/packages/ModelingToolkit/YwkDi/src/systems/jumps/jumpsystem.jl:224
 [6] top-level scope
   @ ~/Documents/catalyst_test/docs_test.jl:70
in expression starting at /Users/user/Documents/catalyst_test/docs_test.jl:70
```

**Comment by yewalenikhil65** [comment]
> When I insert `collect`, it runs until this line:
> 
> ```julia
> dprob   = DiscreteProblem(jumpsys, u₀map, tspan, pars)
> ```
> 
> That results in this error:
> 
> ```
> ERROR: LoadError: MethodError: no method matching CartesianIndices(::Tuple{Vector{Int64}})
> Closest candidates are:
>   CartesianIndices(::Tuple{}) at multidimensional.jl:269
>   CartesianIndices(::R) where {N, R<:Tuple{Vararg{OrdinalRange{Int64, Int64}, N}}} at multidimensional.jl:266
>   CartesianIndices(::Tuple{Vararg{OrdinalRange{var"#s832", var"#s831"} where {var"#s832"<:Integer, var"#s831"<:Integer}, N}}) where N at multidimensional.jl:270
>   ...
> Stacktrace:
>  [1] eachindex(A::Symbolics.Arr{Any, 1})
>    @ Symbolics ~/.julia/packages/Symbolics/S525E/src/arrays.jl:463
>  [2] iterate(A::Symbolics.Arr{Any, 1})
>    @ Base ./abstractarray.jl:1094
>  [3] varmap_to_vars(varmap::Symbolics.Arr{Any, 1}, varlist::Vector{Term{Real, Nothing}}; defaults::Dict{Any, Any}, check::Bool, toterm::Function)
>    @ ModelingToolkit ~/.julia/packages/ModelingToolkit/YwkDi/src/variables.jl:48
>  [4] DiscreteProblem(sys::JumpSystem{RecursiveArrayTools.ArrayPartition{Any, Tuple{Vector{MassActionJump}, Vector{ConstantRateJump}, Vector{VariableRateJump}}}}, u0map::Symbolics.Arr{Any, 1}, tspan::Tuple{Float64, Float64}, parammap::Symbolics.Arr{Any, 1}; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
>    @ ModelingToolkit ~/.julia/packages/ModelingToolkit/YwkDi/src/systems/jumps/jumpsystem.jl:225
>  [5] DiscreteProblem(sys::JumpSystem{RecursiveArrayTools.ArrayPartition{Any, Tuple{Vector{MassActionJump}, Vector{ConstantRateJump}, Vector{VariableRateJump}}}}, u0map::Symbolics.Arr{Any, 1}, tspan::Tuple{Float64, Float64}, parammap::Symbolics.Arr{Any, 1})
>    @ ModelingToolkit ~/.julia/packages/ModelingToolkit/YwkDi/src/systems/jumps/jumpsystem.jl:224
>  [6] top-level scope
>    @ ~/Documents/catalyst_test/docs_test.jl:70
> in expression starting at /Users/user/Documents/catalyst_test/docs_test.jl:70
> ```

@bosonbaas , if symbolics has changed, i guess we need to also modify `maps`in following fashion
```julia
pars = Pair.(collect(k), kv)
u₀map = Pair.(collect(X), u₀)   # map variable to its initial value

```

**Comment by bosonbaas** [comment]
Great, thanks! I can confirm that adding those `collect` statements allows the documentation script to run as expected.

**Comment by isaacsas** [comment]
@yewalenikhil65 could you put in a PR updating the tutorial? thanks!

**Comment by isaacsas** [comment]
@bosonbaas sorry about the issues here! We didn’t catch the breaking change from ModelingToolkit since that didn’t get a major semver update, and our tests didn’t seem to break.

**Comment by bosonbaas** [comment]
No problem, thanks for the quick responses!

**Comment by yewalenikhil65** [comment]
> @yewalenikhil65 could you put in a PR updating the tutorial? thanks!

sure, will do it today

**Comment by isaacsas** [comment]
@yewalenikhil65 can you make the fix to the tutorial a separate PR? It will be quicker to review and merge if it is standalone.

**Comment by yewalenikhil65** [comment]
> @yewalenikhil65 can you make the fix to the tutorial a separate PR? It will be quicker to review and merge if it is standalone.

yes.. sure. i will do it today

**Comment by yewalenikhil65** [comment]
> @yewalenikhil65 can you make the fix to the tutorial a separate PR? It will be quicker to review and merge if it is standalone.

hey @isaacsas , i tried doing this, but can't seem to figure out how to create an another PR(using browser version of github) when already another PR has been submitted earlier.. any directions please ?

**Comment by isaacsas** [comment]
@yewalenikhil65 sorry for the delay. To make a new PR just follow these instructions: https://kbroman.org/github_tutorial/pages/fork.html

**Comment by yewalenikhil65** [comment]
> @YingboMa is there a way to nicely print array variables with subscripts for indices?

@isaacsas ,  @bosonbaas ..I found this way at `ReactionNetworkImporter.jl/`

```julia
using ModelingToolkit
function funcsym(S::Symbol, args...)
           Num(Variable{ModelingToolkit.FnType{Tuple{Any},Real}}(S,args...))
end
species=Any[]
@parameters t
julia>  isempty(species) && (species = [funcsym(:S,i)(t) for i=1:5])
5-element Vector{Num}:
 S₁(t)
 S₂(t)
 S₃(t)
 S₄(t)
 S₅(t)
```
