### ISSUE TITLE
Moving functions to sub package

### ISSUE THREAD

**Issue by TorkelE** [SciML/Catalyst.jl#355]
The package  currently exports these function names:
`mm` , `mmr` , `hill` , `hillr` , `hillar`.

To avoid these potentially overwriting other stuff people have decalred, they could be moved to some other sub package. They would then be imported using e.g.
````
using Catalyst.Functions

**Comment by isaacsas** [comment]
Going to close since I think we decided this isn't need in https://github.com/SciML/Catalyst.jl/pull/458.
