### ISSUE TITLE
Error/warning defining variables with Catalyst tutorial

### ISSUE THREAD

**Issue by jchitpin** [SciML/Catalyst.jl#356]
This is a followup error message to Issue #350  when running the [Generating ReactionSystems Programmatically](https://catalyst.sciml.ai/dev/tutorials/generating_reactions_programmatically/) tutorial from the Catalyst documentation.

When interactively running through the tutorial code line by line, I get the following error when defining the ReactionSystem variables. Specifically, this error triggers for `@variables X[collect(1:N)](t)` but not `@variables k[1:nr]`. The variables `X[1](t)`, `X[2](t)`, etc. are still defined and the `ReactionSystem` is still created when wrapping the variables `X` and `k` with `collect()`.

Note: I'm using Julia version 1.6.2 and Catalyst version 6.14.0.

`julia> @variables k[1:nr]  X[collect(1:N)](t)`
`2-element Vector{Symbolics.Arr{Num, 1}}:`
`Error showing value of type Vector{Symbolics.Arr{Num, 1}}:`
`ERROR: MethodError: no method matching LinearIndices(::Tuple{Vector{Int64}})`
`Closest candidates are:`
`  (::Type{S})(::Complex{Num}) where S<:Union{AbstractFloat, Integer, Complex{var"#s19"} where var"#s19"<:AbstractFloat, Complex{var"#s18"} where var"#s18"<:Integer, AbstractArray} at /home/jchitpin/.julia/packages/Symbolics/H8dtg/src/Symbolics.jl:43`
`  (::Type{S})(::Num) where S<:Union{AbstractFloat, Integer, Complex{var"#s19"} where var"#s19"<:AbstractFloat, Complex{var"#s18"} where var"#s18"<:Integer, AbstractArray} at /home/jchitpin/.julia/packages/Symbolics/H8dtg/src/Symbolics.jl:43
  LinearIndices(::Tuple{}) at indices.jl:454`
`  ...`
`Stacktrace:`
`  [1] LinearIndices(A::Symbolics.Arr{Num, 1})`
`    @ Base ./indices.jl:459`
`  [2] show_delim_array(io::IOContext{IOBuffer}, itr::Symbolics.Arr{Num, 1}, op::Char, delim::String, cl::Char, delim_one::Bool)
    @ Base ./show.jl:1081`
`  [3] show_vector(io::IOContext{IOBuffer}, v::Symbolics.Arr{Num, 1}, opn::Char, cls::Char)
    @ Base ./arrayshow.jl:490`
`  [4] show_vector
    @ ./arrayshow.jl:475 [inlined]`
`  [5] show(io::IOContext{IOBuffer}, X::Symbolics.Arr{Num, 1})
    @ Base ./arrayshow.jl:446`
`  [6] sprint(f::Function, args::Symbolics.Arr{Num, 1}; context::IOContext{Base.TTY}, sizehint::Int64)
    @ Base ./strings/io.jl:103`
`  [7] alignment`
`    @ ./show.jl:2578 [inlined]`
`  [8] alignment(io::IOContext{Base.TTY}, X::Vector{Symbolics.Arr{Num, 1}}, rows::UnitRange{Int64}, cols::UnitRange{Int64}, cols_if_complete::Int64, cols_otherwise::Int64, sep::Int64)`
`    @ Base ./arrayshow.jl:68`
`  [9] _print_matrix(io::IOContext{Base.TTY}, X::AbstractVecOrMat{T} where T, pre::String, sep::String, post::String, hdots::String, vdots::String, ddots::String, hmod::Int64, vmod::Int64, rowsA::UnitRange{Int64}, colsA::UnitRange{Int64})`
`    @ Base ./arrayshow.jl:201`
` [10] #invokelatest#2`
`    @ ./essentials.jl:708 [inlined]`
` [11] invokelatest`
`    @ ./essentials.jl:706 [inlined]`
` [12] print_matrix (repeats 2 times)`
`    @ ./arrayshow.jl:170 [inlined]`
` [13] print_array`
`    @ ./arrayshow.jl:327 [inlined]`
` [14] show(io::IOContext{Base.TTY}, #unused#::MIME{Symbol("text/plain")}, X::Vector{Symbolics.Arr{Num, 1}})`
`    @ Base ./arrayshow.jl:368`
` [15] display(d::REPL.REPLDisplay, mime::MIME{Symbol("text/plain")}, x::Any)`
`    @ REPL /build/julia/src/julia-1.6.2/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:213`
` [16] display(d::REPL.REPLDisplay, x::Any)`
`    @ REPL /build/julia/src/julia-1.6.2/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:225`
` [17] (::REPL.var"#do_respond#61"{Bool, Bool, REPL.var"#72#82"{REPL.LineEditREPL, REPL.REPLHistoryProvider}, REPL.LineEditREPL, REPL.LineEdit.Prompt})(s::REPL.LineEdit.MIState, buf::Any, ok::Bool)`
`    @ REPL /build/julia/src/julia-1.6.2/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:798`

**Comment by yewalenikhil65** [comment]
@jchitpin 
issue resolved here, check discussion. https://github.com/SciML/Catalyst.jl/issues/350
will update the tutorial

**Comment by jchitpin** [comment]
Thank you and apologies for not reading #350 thoroughly!
