### ISSUE TITLE
How to add tests for an array of reaction systems

### ISSUE THREAD

**Issue by yewalenikhil65** [SciML/Catalyst.jl#358]
need to do something like this,
 rn as vector of reactionsystems
```
using Test
for i in length(rn)
    @test all(condition to be checked for rn[i])
end
```
does the scope of @test all() fail to run the test in `test/api.jl` 
https://github.com/SciML/Catalyst.jl/blob/master/test/api.jl

**Comment by ChrisRackauckas** [comment]
Just do it.

**Comment by yewalenikhil65** [comment]
> Just do it.

It works,, thanks !
i was unnecessarily worried
