### ISSUE TITLE
plotting reaction complex network.. 

### ISSUE THREAD

**Issue by yewalenikhil65** [SciML/Catalyst.jl#374]
hi @isaacsas ,
my preliminary way of plotting network as complexes is,
```julia
using LightGraphs,GraphRecipes

function create_graph(incidence::Array{Int,2})
    n=size(incidence)[2]
    graph = DiGraph(n)    # find nodes where edge goes out and edge goes

    v_out = findall(x -> x == -1, incidence) #  edge goes out of vertex
    v_in = findall(x -> x == 1, incidence)  # edge goes in of vertex
    # match the Cartesian index between the two lists, add edge
    for i in v_in
        for o in v_out
            if o[1] == i[1]
                add_edge!(graph, o[2], i[2])
            end
        end
    end
    return graph
end

# to be revised
function plot_network(rs)
    complexes,B = reactioncomplexes(rs)
    graph = create_graph(Array(B'))
    Xₜₑₘₚ = states(rs)
    complexes_names  = []

    for i ∈ 1:length(complexes)
        push!(complexes_names ,
                sum(Xₜₑₘₚ[complexes[i].speciesids].*complexes[i].speciesstoichs))
    end
    graphplot(graph, names = string.(complexes_names),
            nodesize = 0.1, nodeshape = :circle,
            curves = true, fontsize=6)
end


using Catalyst

rn = @reaction_network begin
    k₁, 2A --> B
    k₂, A --> C
    k₃, C --> D
    k₄, B + D --> E
end k₁ k₂ k₃ k₄

gr()
plot_network(rn)

```
it has dependency on `LightGraphs,GraphRecipes` . let me know  your thoughts on this ?
![image](https://user-images.githubusercontent.com/26343789/129096513-2b9f3fad-6763-420f-9f0b-6bb753d0c358.png)

**Comment by isaacsas** [comment]
Is there any Julia graph plotting library that is actively maintained at this point? I'd prefer if all our graph plotting uses the same interface / library. Right now we use the hooks into GraphViz from Catlab. If we are going to switch to something else it would be good to update that plotting code too.

**Comment by isaacsas** [comment]
A few other comments:
1. Take `complexes` and `B` as keyword arguments to `plot_network` to have the user pass them in?
2. Can't you just manually loop through `B` in `create_graph`, thereby avoiding the copy and transpose in `plot_network`. Then you can `push!` onto `v_out` and `v_in` as needed the indices to save.

So `plot_network` should be something like
```julia
function plot_network(rs; complexes, B)
           graph = create_graph(B)   # update `create_graph` to just loop through B appropriately
           Xₜₑₘₚ = states(rs)
           f = rcel -> Xₜₑₘₚ[rcel.speciesid]*rcel.speciesstoich
           complexes_names  = [sum(f, rc) for rc in complexes]
           graphplot(graph, names = string.(complexes_names),
                   nodesize = 0.1, nodeshape = :circle,
                   curves = true, fontsize=6)
end
```

**Comment by isaacsas** [comment]
Hmm, maybe we should just make a CatalystPlots.jl library and offload the current graph plotting code there. Then it will be a natural place for all plotting-related code to live, and basic Catalyst users won't have to pull in dependencies on Plots.jl and such.

**Comment by yewalenikhil65** [comment]
@isaacsas  something like this ??
I updated it a little to accomodate `null` species also, and adjusted `loop` inside `create_graph` to work without transposing `B` matrix !
```julia
function create_graph(incidence::Matrix{Int64})
    n = size(incidence)[1]
    graph = DiGraph(n)    # find nodes where edge goes out and edge goes

    v_out = findall(x -> x == -1, incidence) #  edge goes out of vertex
    v_in = findall(x -> x == 1, incidence)  # edge goes in of vertex
    # match the Cartesian index between the two lists, add edge
    for i in v_in
        for o in v_out
            if o[2] == i[2]
                add_edge!(graph, o[1], i[1])
            end
        end
    end
    return graph
end

# to be revised
function plot_network(rs::ReactionSystem)
    complexes, B = reactioncomplexes(rs)
    graph = create_graph(B)
    Xₜₑₘₚ = species(rs)
    f = rcel -> Xₜₑₘₚ[rcel.speciesid]*rcel.speciesstoich
    complexes_names  = [rc == Catalyst.ReactionComplex{Int64}[] ? 0 : sum(f, rc) for rc in complexes]
    graphplot(graph, names = string.(complexes_names),
            nodesize = 0.1, nodeshape = :circle,
            curves = true, fontsize=6)
end
```
> Is there any Julia graph plotting library that is actively maintained at this point? I'd prefer if all our graph plotting uses the same interface/library. Right now we use the hooks into GraphViz from Catlab. If we are going to switch to something else it would be good to update that plotting code too.

I don't really know the status of graph libraries, but I think `GraphViz` frm `Catlab` could be more active than `LightGraphs`. In addition, asthetically `GraphViz` based current `Catalyst.Graph` gives more nicer graphs !

**Comment by yewalenikhil65** [comment]
Hey @isaacsas  , this page mentions many good visualisation ways to be used along with `LightGraphs.jl`

**Comment by isaacsas** [comment]
Only one of the libraries listed on that webpage has had a commit this year, so most of them don't seem actively maintained. 

Can you put in a PR that uses the current GraphViz code to make the graphs?

**Comment by yewalenikhil65** [comment]
> Can you put in a PR that uses the current GraphViz code to make the graphs?

Yes, I have been trying to read the code from `Catalyst.graphs.jl` but I am not very familiar with the syntax in it yet
Can you please point me to relevant code lines in `Catalyst.graph.jl` for adding edges of the graph?

**Comment by isaacsas** [comment]
https://github.com/SciML/Catalyst.jl/blob/5994cfd427bb0c9406a1b3c9f30bdc3c112ad47c/src/graphs.jl#L286

**Comment by yewalenikhil65** [comment]
I have managed to finish this! Will do a PR today!

**Comment by isaacsas** [comment]
Closed by https://github.com/SciML/Catalyst.jl/pull/380
