### ISSUE TITLE
Error while asignning units as shown in Catalyst readme.md

### ISSUE THREAD

**Issue by yewalenikhil65** [SciML/Catalyst.jl#385]
This could be raised on MTK as well, but since I found this mentioned in the `Catalyst` readme.md, thought to post here
![image](https://user-images.githubusercontent.com/26343789/130268612-de4b8547-1101-47b2-8657-2866d80f254e.png)

I thought `Unitful` was imported by MTK ??
If I add separately Unitful it does rectify this error and runs okay

I think Catalyst can also add `Unitful` as dependency or we could make read.md from catalyst more clear ?

**Comment by isaacsas** [comment]
README is updated to `using Unitful` too. For future reference, you can click the edit button (the pencil) and use that to make a PR with the update yourself.
