### ISSUE TITLE
Constraints in for weak acids and pH equilibrium

### ISSUE THREAD

**Issue by gagnonaa10** [SciML/Catalyst.jl#398]
Transferred from the [Julia Discourse](https://discourse.julialang.org/t/constraints-in-catalyst-jl-for-weak-acids-and-ph-equilibrium/68037)

Hello Everyone,

I was hoping for some guidance on how to incorporate constraints for pH equilibriums constants into a disinfection model I am building in Julia.

A simplified version of the reaction network is here:

```
using OrdinaryDiffEq
using Catalyst
using DifferentialEquations
using Plots
using Latexify

disinfectionmodel = @reaction_network begin
    k1, HOCl + NH3 --> NH2Cl
    k2, NH2Cl --> HOCl + NH3
    k3, HOCl + NH2Cl --> NHCl2
    k4, NHCl2 --> HOCl + NH2Cl
    k5, HOCl + H + Br --> BrCl
    (kf, kf/10^-14), H + OH ↔ H2O
    (kf, kf/10^-9.25), NH3 + H ↔ NH4
    (kf, kf/10^-7.53), OCl + H ↔ HOCl
end 
```

What I am having trouble with now is the constraints associated with the pH dependent equilibrium relationships of weak acids and of pH itself. The full reaction system includes multiple reactions in which H or OH are the products or the reactant. I have done a bit of sleuthing and found Issue #137 which discussed adding constraints.

However, when I tried to utilize the @add_constraints macro mentioned in the [Issue #137](https://github.com/SciML/Catalyst.jl/issues/137) above as shown below, I receive the following an error documented below:

```
@add_constraints disinfectionmodel begin
    log10(H) + log10(OH) = -14
    log10((NH3)*(H)/(NH4)) = -9.25
    log10((OCl)*(H)/(HOCl)) = - 7.53
            end

```

```
LoadError: UndefVarError: @add_constraints not defined
in expression starting at In[4]:1
```

I looked through the Catalyst resource material and was unsuccessful in finding anything that would guide me further but will acknowledge that I am still a bit of a novice when it comes to Julia and programming in general along with interpreting source material. Being able to add these constraints prior to utilizing the differential equation solver will be really helpful!

Thank you for any help anyone can provide!

**Comment by isaacsas** [comment]
Catalyst has never supported this (the depreciated `@add_constraints` macro was only used for finding steady-states and bifurcation analysis). I started towards adding this in https://github.com/SciML/ModelingToolkit.jl/pull/1150 but then we had a bunch of breaking changes here and in ModelingToolkit's namespace handling (which had me rethinking how to internally handle constraints). I'll try to resurrect it soon.

For now I think you could just convert `disinfectionmodel` to an `ODESystem`, add your algebraic constraints as a separate `NonlinearSystem` or `ODESystem` directly in ModelingToolkit, and then use the ModelingToolkit compositional modeling tools to combine the two systems together. Take a look at the ModelingToolkit tutorials to see how to combine systems.

**Comment by isaacsas** [comment]
@gagnonaa10 what are you hoping specifying the constraints will achieve? Right now I am adding the ability to specify the combined system of ODEs and algebraic constraints in https://github.com/SciML/Catalyst.jl/pull/404. However, I don't think ModelingToolkit can do anything with this currently. (i.e. it generally can't reduce the set of ODEs using the constraints; that isn't how structural_simplify works).

**Comment by gagnonaa10** [comment]
@isaacsas Thanks for the help. I want to specify the constraints to include the equilibrium equations (not just the kinetic equations) in the system I want to model. I am not sure if I need to structurally simplify the system, or if that is just a convenience? I have been following the recent commits and comments as well, but not sure what has changed and how I would currently go about this.

The goal is to compose a system with these kinetic relationships
```
    k1, HOCl + NH3 --> NH2Cl
    k2, NH2Cl --> HOCl + NH3
    k3, HOCl + NH2Cl --> NHCl2
    k4, NHCl2 --> HOCl + NH2Cl
    k5, HOCl + H + Br --> BrCl
```
and these equilibrium relationships
```
    log10(H) + log10(OH) = -14
    log10((NH3)*(H)/(NH4)) = -9.25
    log10((OCl)*(H)/(HOCl)) = - 7.53
```
Not sure if this is the right place to continue discussing this, but my current attempt has been using catalyst to compose the CRN, using `convert` to generate an `ODESystem`, and composing it with a `NonLinearSystem` within ModellingToolkit, but so far I have not been successful.

**Comment by isaacsas** [comment]
This will give you an `ODESystem` as you want, but I don't know if ModelingToolkit can handle the resulting DAE system you get
```julia
 disinfectionmodel = @reaction_network dm begin
    k1, HOCl + NH3 --> NH2Cl
    k2, NH2Cl --> HOCl + NH3
    k3, HOCl + NH2Cl --> NHCl2
    k4, NHCl2 --> HOCl + NH2Cl
    k5, HOCl + H + Br --> BrCl
    end k1 k2 k3 k4 k5
osys = convert(ODESystem, disinfectionmodel)
@variables t, H(t), OH(t), NH3(t), NH4(t), OCl(t), HOCl(t)
@named csys = ODESystem([log10(H) + log10(OH) ~ -14, log10((NH3)*(H)/(NH4)) ~ -9.25, log10(OCl*H/HOCl) ~ - 7.53], t,[H,OH,NH3,NH4,OCl,HOCl],[])
@named fullsys = extend(osys, csys)
```
which then has
```julia
julia> equations(fullsys)
10-element Vector{Equation}:
 log10(H(t)) + log10(OH(t)) ~ -14
 log10((H(t)*NH3(t)) / NH4(t)) ~ -9.25
 log10((H(t)*OCl(t)) / HOCl(t)) ~ -7.53
 Differential(t)(HOCl(t)) ~ k2*NH2Cl(t) + k4*NHCl2(t) - k3*HOCl(t)*NH2Cl(t) - k1*HOCl(t)*NH3(t) - k5*Br(t)*H(t)*HOCl(t)
 Differential(t)(NH3(t)) ~ k2*NH2Cl(t) - k1*HOCl(t)*NH3(t)
 Differential(t)(NH2Cl(t)) ~ k4*NHCl2(t) + k1*HOCl(t)*NH3(t) - k2*NH2Cl(t) - k3*HOCl(t)*NH2Cl(t)
 Differential(t)(NHCl2(t)) ~ k3*HOCl(t)*NH2Cl(t) - k4*NHCl2(t)
 Differential(t)(H(t)) ~ -k5*Br(t)*H(t)*HOCl(t)
 Differential(t)(Br(t)) ~ -k5*Br(t)*H(t)*HOCl(t)
 Differential(t)(BrCl(t)) ~ k5*Br(t)*H(t)*HOCl(t)
```
If you have issues actually solving it now though you'd have to ask over there. I don't have any real familiarity with the ModelingToolkit DAE code.

**Comment by isaacsas** [comment]
Also, look through the ModelingToolkit docs some; there are a bunch of tutorials related to working with DAEs that might be helpful for you. Hope that helps!

**Comment by gagnonaa10** [comment]
Thanks. This has been really helpful. I've been able to get the two systems to be connected but when trying to define the `ODE Problem` I received the following stacktrace:

```
ArgumentError: Equations (11), states (10), and initial conditions (10) are of different lengths. To allow a different number of equations than states use kwarg check_length=false.
```

And when I add `check_lengths=false`, I receive the following stacktrace:
```
DimensionMismatch("new dimensions (10, 10) must be consistent with array size 121")
```

I think it is probably prudent to move this back into the Julia Discourse since I am now dealing with trying to solve the problem in ModelingToolkit. I understand the system is overdefined and I am hoping there is another approach to solving this I may not realize.
