### ISSUE TITLE
reversibility and weak reversibility of CRNs

### ISSUE THREAD

**Issue by yewalenikhil65** [SciML/Catalyst.jl#401]
This is as per definitions described in Book [Foundations of Chemical Reaction Network Theory](https://www.springer.com/gp/book/9783030038571)

Example and defintion of reversible reaction as per chapter 6, section 6.5
```julia
import LightGraphs
const LG = LightGraphs
using Catalyst
rn = @reaction_network begin
   (k2, k1), A <--> 2B
   (k4, k3), A + C <--> D
   (k6, k5), D <--> B+E
   (k8, k7), B + E <--> A + C
end k1 k2 k3 k4 k5 k6 k7 k8
complexgraph(rn)
```
![Screenshot from 2021-09-14 03-13-46](https://user-images.githubusercontent.com/26343789/133160501-7da363d7-41fd-4950-8aec-9baaabf001ba.png)
```julia
B = reactioncomplexes(rn)[2]  # incidence matrix
ig = incidencematgraph(B) ;

# create subnetworks
lcs = linkageclasses(ig);
subnets = subnetworks(rn, lcs);
# collecting incidence matrices of subnetworks
 Bᵢ= [reactioncomplexes.(subnets)[1][2],reactioncomplexes.(subnets)[2][2]]
julia> igs= incidencematgraph.(Bᵢ)
2-element Vector{LightGraphs.SimpleGraphs.SimpleDiGraph{Int64}}:
 {2, 2} directed simple Int64 graph
 {3, 6} directed simple Int64 graph

julia> LG.is_strongly_connected(igs[1])
true

julia> LG.is_strongly_connected(igs[2])
true
```

looks good!  Now lets see a case for cyclic case in next comment

**Comment by yewalenikhil65** [comment]
Example of `weakly-reversible` and but `reversible` as per definition from the book

```julia
rn = @reaction_network begin
   (k2, k1), A <--> 2B
   (k4, k3), A + C <--> D
    k5, D --> B+E
    k6, B + E --> A + C
end k1 k2 k3 k4 k5 k6
complexgraph(rn)
```
![Screenshot from 2021-09-14 03-28-21](https://user-images.githubusercontent.com/26343789/133162039-176fc108-31b0-4482-a3f6-3a63d82b92b5.png)

```julia
B = reactioncomplexes(rn)[2]  # incidence matrix
ig = incidencematgraph(B) ;
# create subnetworks
lcs = linkageclasses(ig);
subnets = subnetworks(rn, lcs);
# collecting incidence matrices of subnetworks
 Bᵢ= [reactioncomplexes.(subnets)[1][2],reactioncomplexes.(subnets)[2][2]]
julia>  igs= incidencematgraph.(Bᵢ)
2-element Vector{LightGraphs.SimpleGraphs.SimpleDiGraph{Int64}}:
 {2, 2} directed simple Int64 graph
 {3, 4} directed simple Int64 graph

julia>  LG.is_strongly_connected(igs[1])
true

julia>  LG.is_strongly_connected(igs[2])
true

```

@isaacsas  , i think you are right ! is_strongly_connected from Lightgraphs does consider cyclic as strongly connected too. this is good, I will make a PR on this ! but we need `cyclic` also to differentiate between reversible and weakly reversible

**Comment by yewalenikhil65** [comment]
To summarise from the book,
`reversible` reactionsystem should have all the subnetworks `strongly connected` but `non-cyclic`  i.e. only direct connections and reverse connections allowed

`weakly_reversible` reactionsystem may have a one or more subnetworks which are `cyclic` and others are strictly `non-cyclic and strongly connected`

any other category, is neither reversible nor weakly reversible

**Comment by yewalenikhil65** [comment]
bdw @isaacsas , is this https://catalyst.sciml.ai/dev/api/catalyst_api/#Catalyst.subnetworks function description not appearing good because of 4 chars tab issue ?

**Comment by isaacsas** [comment]
Probably something like that.

**Comment by isaacsas** [comment]
Regarding weak reversibility; I don't think you need to do anything about cycles. Just check every subnetwork corresponding to a linkage class is strongly connected.

For reversibility you can just count how many times each pair of reaction complex indices appear in a reaction (order them in the pair by complex integer id, so if A=1 and B=2, A --> B and B --> A both give the pair (1,2)). You can use a dict that maps pair to count, and update/calculate it by looping through reactions. Then you check the counts are all 2. (You could also do this by having LightGraphs make the adjacency matrix for the incidence graph and then checking if it is symmetric, but that will be more expensive and memory heavy I think.)

**Comment by yewalenikhil65** [comment]
> Regarding weak reversibility; I don't think you need to do anything about cycles. Just check every subnetwork corresponding to a linkage class is strongly connected.
> 
> For reversibility you can just count how many times each pair of reaction complex indices appear in a reaction (order them in the pair by complex integer id, so if A=1 and B=2, A --> B and B --> A both give the pair (1,2)). You can use a dict that maps pair to count, and update/calculate it by looping through reactions. Then you check the counts are all 2. (You could also do this by having LightGraphs make the adjacency matrix for the incidence graph and then checking if it is symmetric, but that will be more expensive and memory heavy I think.)

thanks for inputs. i will check on this tomorrow

**Comment by yewalenikhil65** [comment]
> Regarding weak reversibility; I don't think you need to do anything about cycles. Just check every subnetwork corresponding to a linkage class is strongly connected.
> 

```julia
function is_weakly_reversible(rs::ReactionSystem; incidencemat = reactioncomplexes(rs)[2])
    ig = incidencematgraph(incidencemat)
    lcs = linkageclasses(ig)
    subnets = subnetworks(rs, lcs)
    igs = [incidencematgraph(reactioncomplexes(subrs)[2]) for subrs in subnets]
    all([LG.is_strongly_connected(ig) for ig in igs])
end

```
@isaacsas , any point in allowing `incidencemat` as sparse or dense options?

**Comment by isaacsas** [comment]
Since anyone calling this is likely to have also called `deficiency`,  I’d suggest taking the subnetworks and linkage classes as input.

**Comment by isaacsas** [comment]
`is_reversible` shouldn't need the subnetworks at all. I think it should be able to be made just using `reactioncomplexmap` and counting like I suggested, which would avoid a whole bunch of intermediate matrices and graphs being allocated.

For `is_weakly_reversible` I'd suggest using a loop; you don't need to store all the graphs simultaneously, just generate each one in the loop and check it is strongly connected. As soon as you find one that is not strongly connected you can return false. If the loop finishes you return true.

**Comment by isaacsas** [comment]
The shortest `is_reversible` implementation is probably (but not the most memory efficient)
```julia
# here ig is the incidence graph of the full system
function isreversible(ig)
    ig == LG.reverse(ig)
end
```
If the approach I suggested didn't make sense you can just do this and I'll work to optimize it later.

**Comment by isaacsas** [comment]
One question I guess to think about; is how does the null state count towards reversibility? i.e. is a system with `A <--> ∅` considered reversible or does having any open reactions preclude being reversible? I don't know the convention here.

**Comment by yewalenikhil65** [comment]
> One question I guess to think about is how does the null state count towards reversibility? i.e. is a system with `A <--> ∅` considered reversible or does having any open reactions preclude being reversible? I don't know the convention here.

I will try to dig about this. I too am not aware. About using your approach I am think over it too, just that for now this approach is what came to mind first

**Comment by isaacsas** [comment]
If you want to PR using `LG.reverse` for now that is fine. It is likely a user will need `ig` anyways for the deficiency calculation, in which case this probably isn't that much more expensive than what I had in mind (I think).

**Comment by yewalenikhil65** [comment]
> If you want to PR using `LG.reverse` for now that is fine. It is likely a user will need `ig` anyways for the deficiency calculation, in which case this probably isn't that much more expensive than what I had in mind (I think).

yes.. i will add PR using `LG.reverse` only for now. JUst searching a little for tests to be added from books / notes

**Comment by isaacsas** [comment]
Feinberg's book has a bunch of small systems that he illustrates deficiency and weak reversibility on I think.

**Comment by yewalenikhil65** [comment]
> Since anyone calling this is likely to have also called `deficiency`, I’d suggest taking the subnetworks and linkage classes as input.

i think for `is_weakly_reversible` only subnetworks are required as input
```julia
"""
    is_reversible(subnetworks)

Given the subnetworks corresponding to the each linkage class of reaction network,
determines if the reaction network is weakly reversible or not.
"""
function is_weakly_reversible(subnets::Vector{ReactionSystem})
    igs = [incidencematgraph(reactioncomplexes(subrs)[2]) for subrs in subnets]
    all([LG.is_strongly_connected(ig) for ig in igs])
end
```

```julia
"""
    is_reversible(incidencegraph)

Given an incidence graph of the reaction network, returns if the network is reversible or not
"""
function is_reversible(ig::LG.SimpleDiGraph)
    reverse(ig) == ig
end
```

**Comment by yewalenikhil65** [comment]
> Feinberg's book has a bunch of small systems that he illustrates deficiency and weak reversibility on I think.

do you recommend tests to be included in same api.jl or create a new file ?

**Comment by isaacsas** [comment]
You can just add them at the end of the current file. I may clean things up and split into multiple files later this week.

**Comment by yewalenikhil65** [comment]
https://github.com/SciML/Catalyst.jl/pull/406

**Comment by yewalenikhil65** [comment]
> One question I guess to think about is how does the null state count towards reversibility? i.e. is a system with `A <--> ∅` considered reversible or does having any open reactions preclude being reversible? I don't know the convention here.

@isaacsas , i checked this in https://hal.inrae.fr/hal-02794650/document , Page 12, second example on the page. our functions give the expected the result. Null state is counted as a complex and `A <--> 0` is considered reversible
