### ISSUE TITLE
Settling time of CRN (i.e. time taken for each species to reach steadystate) 

### ISSUE THREAD

**Issue by yewalenikhil65** [SciML/Catalyst.jl#403]
Settling time of a chemical reaction network(CRN) is defined as, time taken by each species(as each species might take different time span to reach their steady state..especially like in stiff CRNs) to each equilibrium, (with an assumption that CRN does have a unique steady-state) 

Any thoughts on how to calculate this time as `Vector{Float}` ? 

Note : This should be applicable to any general dynamical system admitting a unique steady state, and not just CRNs

**Comment by isaacsas** [comment]
You’d need to be more precise about what you mean mathematically as ODE solutions don’t reach stable steady-states in finite time; they only approach them as t becomes infinite. So perhaps you mean the time to get within a certain distance of the steady-state, or something like the asymptotic rate of approach to the steady-state?

In any case though, this feels like functionality that any ODE system could use, so might not be Catalyst specific (i.e. is better housed in OrdinaryDiffEq, SteadyStateDiffEq or maybe one of he dynamical systems packages).

**Comment by TorkelE** [comment]
As Sam says, as long as you know how to define having "reached" the steady state this shouldn't be very hard.

Create an ODEProblem in your given initial state, and simulate it with a callback that checks every step and terminates it if some condition of proximity to the steady state is fulfilled. Then return the final time value of the simulation.

If you know the steady state you could probably do the same, but have some threshold where, if the solution does not change significantly enough, you consider the steady state reached (might yield a false settling time, but I don't think this can be avoided if you don't actually know the steady state).

**Comment by isaacsas** [comment]
In fact there is a callback for terminating at steady-state already, which will allow you to pass a function that decides if the system has reached steady-state: https://diffeq.sciml.ai/stable/features/callback_library/#TerminateSteadyState.

**Comment by yewalenikhil65** [comment]
@isaacsas You are right! I meant the time to get in some Epsilon distance of steady state. 

@TorkelE @isaacsas  thanks for the hint with callbacks. I think this might be what I was looking for.
