### ISSUE TITLE
conservation of energy

### ISSUE THREAD

**Issue by yangmingyuan380** [SciML/Catalyst.jl#424]
Hello, I'm very grateful that you've developed such a useful tool, and I'm now trying to build a counter-application that has some problems. 
In general, the chemical equation needs to be calculated taking into account the reaction dynamics equation and the energy conservation equation, and the reaction rate k is also highly correlated with temperature, so how to add calculations about radon and temperature to the equation.

**Comment by isaacsas** [comment]
Sorry, I'm not sure I understand your question. Can you be more precise about what you want to do (i.e. give some example code or write it out mathematically)? I'm not sure how you want to account for energy conservation, or temperature in the rates, or what reaction dynamics refers to.
