### ISSUE TITLE
Merging more than one `subnetworks` using merge!

### ISSUE THREAD

**Issue by yewalenikhil65** [SciML/Catalyst.jl#439]
Now that we have `subnetworks` corresponding to different linkage classes of the network, does it make sense to extend the `merge!` function to merge more than one `reactionSystems` as could be the case in merging subnetworks to form original network. (I do not yet know why one would need doing this if one already knows a original network)

**Comment by isaacsas** [comment]
I think it is fine as is. There is also `extend` via ModelingToolkit which generates a new `merged` system.
