### ISSUE TITLE
Error in tutorial "Generating ReactionSystems Programmatically"

### ISSUE THREAD

**Issue by bsvisser** [SciML/Catalyst.jl#450]
When I try to run the code from the [Generating ReactionSystems Programmatically](https://docs.juliahub.com/Catalyst/QGu8a/6.11.0/tutorials/generating_reactions_programmatically/#Generating-ReactionSystems-Programmatically) tutorial, I get an error for generating reactions.

Code:
```julia
# vector to store the Reactions in
rx = []              
for n = 1:nr
    # for clusters of the same size, double the rate
    if (vᵢ[n] == vⱼ[n]) 
        push!(rx, Reaction(k[n], [X[vᵢ[n]]], [X[sum_vᵢvⱼ[n]]], [2], [1]))
    else
        push!(rx, Reaction(k[n], [X[vᵢ[n]], X[vⱼ[n]]], [X[sum_vᵢvⱼ[n]]], 
                           [1, 1], [1]))
    end
end
rs = ReactionSystem(rx, t, X, k)
```

Error message:
```
MethodError: no method matching CartesianIndices(::Tuple{Vector{Int64}})
Closest candidates are:
  (::Type{S})(::Complex{Num}) where S<:Union{AbstractFloat, Integer, Complex{var"#s145"} where var"#s145"<:AbstractFloat, Complex{var"#s144"} where var"#s144"<:Integer, AbstractArray} at C:\Users\admin-brent\.julia\packages\Symbolics\Cmx10\src\Symbolics.jl:124
  (::Type{S})(::Num) where S<:Union{AbstractFloat, Integer, Complex{var"#s145"} where var"#s145"<:AbstractFloat, Complex{var"#s144"} where var"#s144"<:Integer, AbstractArray} at C:\Users\.julia\packages\Symbolics\Cmx10\src\Symbolics.jl:124
  CartesianIndices(::Tuple{}) at multidimensional.jl:269
  ...

Stacktrace:
 [1] getindex(x::Symbolics.ArrayOp{AbstractVector{Real}}, idx::Int64)
   @ Symbolics C:\Users\.julia\packages\Symbolics\Cmx10\src\array-lib.jl:23
 [2] getindex(x::Symbolics.Arr{Num, 1}, idx::Int64)
   @ Symbolics C:\Users\.julia\packages\Symbolics\Cmx10\src\array-lib.jl:84
 [3] top-level scope
   @ .\In[6]:0
 [4] eval
   @ .\boot.jl:360 [inlined]
 [5] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base .\loading.jl:1116
```

Can anyone help me figure out where this is going wrong? Is this an error in the tutorial?

**Comment by yewalenikhil65** [comment]
@bsvisser this is because of updated Symbolics.jl  and also some new updates in Catalyst. I see now that symbolic array indexing is reverted back to earlier ways. I just forgot to update this tutorial accordingly.I will fix this tutorial quickly.

**Comment by yewalenikhil65** [comment]
@bsvisser you have linked an old tutorial. I didn't notice it before. Please check https://catalyst.sciml.ai/dev/tutorials/generating_reactions_programmatically/  
hope you are using an updated version of Catalyst ! Currently its v10.2.0

**Comment by isaacsas** [comment]
@yewalenikhil65 is the tutorial working on 10.2 then?

**Comment by yewalenikhil65** [comment]
> @yewalenikhil65 is the tutorial working on 10.2 then?

@isaacsas Yes, it's working

**Comment by bsvisser** [comment]
@yewalenikhil65 Thank you for the correct link. It indeed works properly now!
