### ISSUE TITLE
provide defaults using @reaction_network

### ISSUE THREAD

**Issue by Sov-trotter** [SciML/Catalyst.jl#464]
`ReactionSystem` has a `defaults` field to allow for "initial conditions and/or parameter values" . 

But when I create a `ReactionSystem` using the `@reaction_network` macro, it's not currently possible to provide default values and `Catalyst.get_defaults(rn)` returns an empty `Dict`.

**Comment by isaacsas** [comment]
Yeah, I don't think there is a nice way to do or add this with the current macro.

What we were discussing is making an intermediate level `rx = @reaction k, A+B --> C` macro that is more explicit and could hopefully keep the compact notation of the current macro, while allow the flexibility of using the underlying ModelingToolkit `@parameters` and `@variables` macros to species parameters and species (and default values).

**Comment by isaacsas** [comment]
@Sov-trotter this should work in the next release (or using master):
```julia
rn = @reaction_network begin
    α, S + I --> 2I
    β, I --> R
end α β
defs = [:S => 999.0, :I => 1.0, :R => 0.0, :α => 1e-4, :β => .01]
setdefaults!(rn, defs)
op = ODEProblem(rn, [], tspan, [])
sol = solve(op, Tsit5())
```
