### ISSUE TITLE
Add support for symbolic events

### ISSUE THREAD

**Issue by isaacsas** [SciML/Catalyst.jl#499]

**Comment by paulflang** [comment]
Is this for `ReactionSystem`? Cause AFAIK `ReactionSystem` does not yet have a field for events. Therefore, if a user wants to import an SBML with events, they cannot go via `ReactionSystem(model::SBML.Model)`, but must go via `ODESsystem(model::SBML.Model)`. cc: @anandijain

**Comment by isaacsas** [comment]
Yes for ReactionSystem.

**Comment by paulflang** [comment]
Idk at top of my head. But I am running the test suite atm and will let you know.

**Comment by isaacsas** [comment]
Note to self: we should also make sure to propagate events from constraint subsystems.

**Comment by isaacsas** [comment]
Closed by https://github.com/SciML/Catalyst.jl/pull/514 for ODESystems with continuous events (which are the only supported system-event type to my knowledge).
