### ISSUE TITLE
ReducedODESystem: Automatic simplification of chemical reaction ODE systems via derived conservation laws

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/Catalyst.jl#500]
We have https://catalyst.sciml.ai/dev/api/catalyst_api/#Catalyst.conservationlaws, so why don't we make the usage simpler? 

Take a look at ROBER:

```julia
  D(y₁) ~ -k₁*y₁+k₃*y₂*y₃
  D(y₂) ~  k₁*y₁-k₂*y₂^2-k₃*y₂*y₃
  D(y₃) ~  k₂*y₂^2
```

In chemical reaction form, if we could prove that `y₁ + y₂ + y₃ = C`, then we know that `y₁ = C -  y₂ - y₃`, and thus we have the ODE:

```julia
  D(y₂) =  k₁*(C -  y₂ - y₃)-k₂*y₂^2-k₃*y₂*y₃
  D(y₃) =  k₂*y₂^2
```

or in MTK form, you'd just write it as a DAE:

```julia
  y₁ ~ C -  y₂ - y₃
  D(y₂) ~  k₁*y₁-k₂*y₂^2-k₃*y₂*y₃
  D(y₃) ~  k₂*y₂^2
```

and let `structural_simplify` take care of it from there. I wonder if this can greatly improve computational speed in some cases, along with accuracy, since making implicit constraints explicit will also improve the numerical stability.

**Comment by isaacsas** [comment]
https://github.com/SciML/Catalyst.jl/pull/340 started on this.

The original idea was to generate a new `ReactionSystem` with the conserved species removed, but I must admit that I wonder if that is actually a bad idea for jumps (fine for ODEs) since it makes the system potentially have non-mass action jumps I think.

**Comment by isaacsas** [comment]
It would also be useful for generating non-singular Jacobians for bifurcation analysis.

**Comment by isaacsas** [comment]
I'm working on this now. I want to see what other packages do. I'm leaning towards stashing the species elimination formulas and list of dependent species within a system, and then applying them automatically when `convert`ing. Having a kwarg to control this behavior makes sense as @TorkelE suggested.

**Comment by isaacsas** [comment]
closed by https://github.com/SciML/Catalyst.jl/pull/506

```julia
julia> using Catalyst

julia> rober = @reaction_network begin
       k1, A --> B
       k2, B + B --> C + B
       k3, B + C --> A + C
       end k1 k2 k3
julia> osys = convert(ODESystem, rober; remove_conserved=true)
Model ##ReactionSystem#292 with 2 equations
States (2):
  A(t)
  B(t)
Parameters (4):
  k1
  k2
  k3
  _ConLaw[1] [defaults to A(t) + B(t) + C(t)]

julia> equations(osys)
2-element Vector{Equation}:
 Differential(t)(A(t)) ~ k3*(_ConLaw[1] - A(t) - B(t))*B(t) - k1*A(t)
 Differential(t)(B(t)) ~ k1*A(t) - (1//2)*k2*(B(t)^2) - k3*(_ConLaw[1] - A(t) - B(t))*B(t)
```
