### ISSUE TITLE
making combinatoric_ratelaws more flexible

### ISSUE THREAD

**Issue by isaacsas** [SciML/Catalyst.jl#507]
As @paulflang brought up via Slack it would be helpful for SBML if this could be specifed at a per-reaction level, but perhaps just being able to set it when building a `ReactionSystem` would be ok too?

**Comment by isaacsas** [comment]
One problem with making it per reaction is that we'd probably want a way to specify it via the DSL on a per-reaction basis too.

**Comment by paulflang** [comment]
Thanks for creating this issue, @isaacsas . I think it is fine if it is just specified on the `ReactionSystem` level as you suggest.

**Comment by isaacsas** [comment]
OK, great. I'll try to add that in after I finish up the conservation law PR and before making a breaking release.

**Comment by paulflang** [comment]
Thanks!

**Comment by isaacsas** [comment]
Closed by https://github.com/SciML/Catalyst.jl/pull/510
