### ISSUE TITLE
Matricial ts theory

### ISSUE THREAD

**Issue by Leticia-maria** [SciML/Catalyst.jl#555]
Does catalyst have a matrix of stoichiometric coefficients between reactants and transition states? I can implement it, if convenient (Dr. @isaacsas, it is for Overreact.jl 😄 )

**Comment by Leticia-maria** [comment]
Thanks for your attention

**Comment by isaacsas** [comment]
Do you mean `substoichmat`, `prodstoichmat`, or `netstoichmat`?

**Comment by isaacsas** [comment]
Otherwise I’m not sure what you are looking for.

**Comment by yewalenikhil65** [comment]
I think it is `complexstoichmat`

**Comment by isaacsas** [comment]
Too many to remember. Thanks for adding that @yewalenikhil65.

**Comment by Leticia-maria** [comment]
I figured it out, it is ```incidencemat```. Thanks for your help

**Comment by Leticia-maria** [comment]
I have another question, I am not sure if I should open another issue for it: When I run ```reactioncomplexes```, I received this warning:

```Julia
Julia>  rn = @reaction_network begin
               k, A --> B
               a, B --> A
               end k a
Model ##ReactionSystem#315
States (2):
  A(t)
  B(t)
Parameters (2):
  k
  a
Julia> reactioncomplexes(rn)
(WARNING: both Symbolics and ModelingToolkit export "infimum"; uses of it in module Catalyst must be qualified
WARNING: both Symbolics and ModelingToolkit export "supremum"; uses of it in module Catalyst must be qualified

**Comment by isaacsas** [comment]
That’s a long-standing ModelingToolkit/Symbolics issue and shouldn’t affect anything in Catalyst.

**Comment by Leticia-maria** [comment]
Okay, perfect! Thanks so much
