### ISSUE TITLE
Reaction rates with greek letter is followed by a number cause latexify error

### ISSUE THREAD

**Issue by gaurav-arya** [SciML/Catalyst.jl#566]
MWE:
```
using Catalyst, Latexify

rn = @reaction_network begin
    λ1, A --> B
end λ1

@show latexify(rn)
latexify(rn) |> render
```
The produced LaTeX string:
```
L"\begin{align*}
\require{mhchem}
\ce{ A &->[${\lambda}1$] B}
\end{align*}
```
And the rendered output:
![image](https://user-images.githubusercontent.com/43899491/200696003-e9d6e6c2-7955-439d-b251-12e466110cec.png)
where the error seems to come from the `${\lambda}1$`.

(On Catalyst version 12.3.1)

**Comment by isaacsas** [comment]
This compiles fine for me in LaTeXiT. Where are you running this that you get an error? Pluto, Jupyter, or a tex document?

**Comment by gaurav-arya** [comment]
Hmm, I can only reproduce it when passing it to the `render` function of `Latexify` (as in the last line of the code snippet), and even then only when in VSCode (it works fine in the REPL...)

**Comment by gaurav-arya** [comment]
So my MWE is to press the triangle to run the file in the below image (given the specificity of this situation, probably not a bug with `Catalyst`, but still strange):

![image](https://user-images.githubusercontent.com/43899491/200697472-4c99ed2e-902d-4459-966f-22b134f8a335.png)

**Comment by isaacsas** [comment]
Pluto just outputs
```
\begin{align*} \require{mhchem} \ce{ A &->[${\lambda}1$] B} \end{align*}
```
instead of showing the compiled Latex, and Jupyter displays the compiled tex but with dollar signs around $\lambda1$.

Not sure there is anything to really be done here in Catalyst though. It seems like we are generating correct Latex as I understand it. The issue is that these different tools interpret it differently (probably because their Katex or MathTex engine doesn't support all of Latex).

**Comment by isaacsas** [comment]
Maybe open an issue that Latex rendering is not working on this example with the generated code on the VSCode pluggin repo or on the Latexify repo? Given the Latex compiles ok this seems more an issue with one of those and how they are trying to display the Latex.

At the end of the day though, the mchem package is finicky in Katex/MathTex, so this might just not be easy to get working with it...

**Comment by gaurav-arya** [comment]
It seems to be an issue with the MIME type `MIME"juliavscode/html"` that's chosen by `Latexify`'s `render` function when in VSCode. So yup, definitely not a `Catalyst` issue, I'll make an issue in `Latexify`. Thanks for your prompt replies!
