### ISSUE TITLE
Distinguishing species from normal variables and handling non-rx equations

### ISSUE THREAD

**Issue by isaacsas** [SciML/Catalyst.jl#569]
Right now we essentially identify species and states as the same thing; I was thinking it might make sense to add a `@species` macro and use metadata to tag species as distinct from states. With this change `species(rn)` would filter the species from the internal state list, while `states(rn)` would return all states (species and non-species). `get_states(rn)` would give the underlying vector that includes both.

One benefit to this approach is we could more easily then allow non-reaction equations as an additional field within the `ReactionSystem`, and drop the whole constraint system approach (which is clunky to manage internally).

I'd be curious to hear other's thoughts though. (This would be a breaking change, but probably in a way that would not impact many people since we don't even have a tutorial on adding constraint systems yet.)

**Comment by TorkelE** [comment]
I have never really worked with mixed CRN/Other stuff models, so cannot really say how useful this would be.

For constraint system, you don't mean systems where constraints are implicitly implied by e.g. initial conditions, like:
```
@reaction_network begin
    (k1,k2), X <--> Y
end k1 k2
```
but instead some other type of contained system, right?

**Comment by isaacsas** [comment]
I mean where you have a coupled set of additional ODEs or algebraic equations (like the Hodgkin-Huxley example I did in our tutorial), which right now you pass as a constraint `ODESystem` or `NonlinearSystem`. For example, one can have an ODE for the change in volume, which wouldn't necessarily make sense to model as a reaction.

**Comment by TorkelE** [comment]
Got it.

I will avoid making strong comments about stuff I am unfamiliar with the scope/interest of/in, but sounds good to me.

**Comment by isaacsas** [comment]
Closed by https://github.com/SciML/Catalyst.jl/pull/585
