### ISSUE TITLE
Unable to remake large network `ODEProblem` for ensemble calculation

### ISSUE THREAD

**Issue by joegilkes** [SciML/Catalyst.jl#575]
I'm working with a set of large reaction networks, assembled programatically through the `Reaction`/`ReactionSystem` interface. I have predicted rate constants, each of which has a predictive uncertainty that I'm trying, through various means, to propagate through an ODE solve. One method I'm trying is to do Monte Carlo sampling of the rate constants by sampling from normal distributions for each rate constant in an `EnsembleProblem`:

```julia
p_dist = [truncated(Normal(r, ru), max(r-(4*u), 0.0), r+(4*u)) for (r, u) in zip(rates, rate_uncertainties)]

oprob = ODEProblem(rs, u0map, tspan, pmap, jac=true, sparse=true)
function prob_func(prob, i, repeat)
    remake(prob, p=rand.(p_dist))
end
ensemble_prob = EnsembleProblem(oprob, prob_func=prob_func)
sol = solve(ensemble_prob, QNDF(), EnsembleSerial(); trajectories=n, solvecall_kwargs...)
```

I'm having a problem calling `remake()` on the `ODEProblem` though. I can pair it down to just forming the `ODEProblem` and calling `remake()`, and the code gets stuck there. It doesn't crash, and a single CPU core stays pinned to 100% until I interrupt the execution. I've left this for over 2 hours without any progress.

As far as I understand, the point of calling `remake()` is to avoid recompiling the whole `ODEProblem` again, so it should be faster than making the `ODEProblem`. The reaction network I'm working on now is about 7000 reactions in size, and spans over ~1300 species, so ~ 7000 parameters over ~ 1300 ODEs. Making the initial `ODEProblem` (including making the sparse analytical Jacobian) takes about 3 minutes, so `remake` should be faster than that.

I can't figure out why `remake` would be getting stuck to this extent - it works for much smaller systems (36 reactions, 28 species) so I can only assume it's a dimensionality problem?

**Comment by isaacsas** [comment]
This sounds like it is probably a ModelingToolit or SciMLBase issue, but to debug it would be helpful if you could post a complete MWE we can run.

**Comment by joegilkes** [comment]
Found the issue, a pair of fresh eyes this morning really helped. It turns out that some predicted rate constants had zero uncertainty due to the reactions being barrierless, and truncating a Normal distribution with zero standard deviation exactly at its mean causes the process to hang indefinitely. Fixing this lets `remake` run as intended.

Sorry for not catching this sooner, thanks for the response!

**Comment by isaacsas** [comment]
Glad you found the issue (and it wasn’t in Catalyst!).
