### ISSUE TITLE
Separate /test/Project.toml environment file

### ISSUE THREAD

**Issue by TorkelE** [SciML/Catalyst.jl#578]
If I get it right, according to 
https://pkgdocs.julialang.org/v1/creating-packages/#Test-specific-dependencies-in-Julia-1.2-and-above
the current dogma is to have one Project.toml file for the package in the main folder, and then a separate Project.toml file in /test for which the tests run. Currently, we only have one in the main folder, which has a section `[extras]` to handle test packages.

Would it make sense to change to the set up with two different ones? I think one advantage would be that it is easier to activate the test environment to run the tests with the sam environment as CI. 
(currently I activate the main one, but that does not provide the packages unique for the tests)

**Comment by TorkelE** [comment]
(If people think this make sense I am happy to do it, however, wanted to check since I think others might know this stuff better than me, and there might be some reason I am unaware of why things are set up as they are)

**Comment by isaacsas** [comment]
Sounds good to me! Our current setup is just historical, based on the older testing style. I agree it would be nice to have a self-contained testing environment one can manually activate.

**Comment by TorkelE** [comment]
Great, will set it up after the updated DSL syntax thing is done.

**Comment by TorkelE** [comment]
Julia 1.10 will probably have functionality making this simpler. So we will hold this off until then: https://discourse.julialang.org/t/link-project-toml-files-or-make-test-prokect-toml-depend-on-main-package-one/93223/3
