### ISSUE TITLE
Change Docoument outline

### ISSUE THREAD

**Issue by TorkelE** [SciML/Catalyst.jl#581]
Currently, the documentation is mostly concentrated in one big category called "Tutorials". I think by splitting this category we might make them a bit easier to read. Here follows a few suggestions:

## Current version
This is what we currently have:
#### Catalyst for new Julia users
- Introduction to Catalyst and Julia for new Julia users
#### Tutorials
- Using Catalyst
- The Reaction DSL
- Programmatic Construction of Symbolic Reaction Systems
- Basic Chemical Reaction Network Examples
- Compositional Modeling of Reaction Systems
- Parametric Stoichiometry
- Network Analysis in Catalyst
- Finding Steady States through Homotopy Continuation
- Bifurcation Diagrams
- Parameter Estimation
- Smoluchowski Coagulation Equation
#### API
- Catalyst.jl API

## Alternative 1
Here we basically split the Tutorial section into a section describing the functionalities of Catalyst (basically what stuff is implemented in Catalyst) and a Tutorial section (giving tutorials for various types of analysis, typically involving lots of non-Catalyst functionality).
#### Catalyst for new Julia users
- Introduction to Catalyst and Julia for new Julia users
#### Catalyst functionality
- Using Catalyst
- The Reaction DSL
- Programmatic Construction of Symbolic Reaction Systems
- Basic Chemical Reaction Network Examples
- Compositional Modeling of Reaction Systems
- Parametric Stoichiometry
#### Tutorials
- Network Analysis in Catalyst
- Finding Steady States through Homotopy Continuation
- Bifurcation Diagrams
- Parameter Estimation
- Smoluchowski Coagulation Equation
#### API
- Catalyst.jl API

## Alternative 2
Here we revamp the "Catalyst for new Julia users" section to an "Introduction to Catalyst" with separate introductions depending on whether someone knows Julia or not. We also call the section split off from tutorials "Model creation and simulation", and it gathers stuff on how to create a model in catalyst and how to simulate it (including a new section on the latter).
#### Introduction to Catalyst
- Introduction to Catalyst for those familiar with Julia [NEW]
- Introduction to Catalyst and Julia for new Julia users
#### Model creation and simulation
- Using Catalyst
- The Reaction DSL
- Programmatic Construction of Symbolic Reaction Systems
- Basic Chemical Reaction Network Examples
- Compositional Modeling of Reaction Systems
- Parametric Stoichiometry
- Advanced simulation options [NEW]
#### Tutorials
- Network Analysis in Catalyst
- Finding Steady States through Homotopy Continuation
- Bifurcation Diagrams
- Parameter Estimation
- Smoluchowski Coagulation Equation
#### API
- Catalyst.jl API

## Alternative 3
This is basically a combination of the previous two, but we create a new section on Example networks, containing both the basic ones and the smoluchowski one.
#### Introduction to Catalyst
- Introduction to Catalyst for those familiar with Julia [NEW]
- Introduction to Catalyst and Julia for new Julia users
#### Catalyst functionality
- Using Catalyst
- The Reaction DSL
- Programmatic Construction of Symbolic Reaction Systems
- Compositional Modeling of Reaction Systems
- Parametric Stoichiometry
- Advanced simulation options [NEW]
#### Tutorials
- Network Analysis in Catalyst
- Finding Steady States through Homotopy Continuation
- Bifurcation Diagrams
- Parameter Estimation
#### Example chemical reaction networks
- Basic Chemical Reaction Network Examples
- Smoluchowski Coagulation Equation
#### API
- Catalyst.jl API

## Summary
We can do some combination of the various changes suggested here. Also, is there a reason that the API section is split into several minor sections, but only contain one such section (unlike FAQs and Home that are just single docs)?

**Comment by TorkelE** [comment]
Some of my thoughts:
- I definitely think the Tutorial section should be split into at least 2 sections. 
- I am not sure what is the natural fit. One section should be tutorials, then the other could be core functions implemented in Catalyst. Alternatively, we could have one section for creating models, and one for simulating them. The second would only be 2 subsections (basics and advanced). However, if we split "Introduction to Catalyst" into two any reader will already be familiar with model creation when they get to the simulation part, so this would work out. 
- I like the idea of having a separate Example CRN section, as the basic one doesn't really fit anywhere. However, the "Smoluchowski Coagulation Equation" subsection maybe is more of a tutorial in programmatically creating a CRN than a specific CRN example (maybe the title should say this). Having a section with only one subsection seems a bit little.
- I'm vaguely in favour of creating a "Introduction to Catalyst" section with two subsections. I think having more than one "Introduction to Catalyst and Julia for new Julia users" subsection won't make sense (and further Julia introduction should just be directed to the general Julia intro). Adding a Catalyst intro for those familiar with Julia seems sensible, especially since we do not have a dedicated such section.
-  Creating a "Advanced simulation options" subsection I think is a good idea. It could contain some generally interesting stuff like ensemble solving, callbacks, and plotting options. Then they could point to DiffEq docs for more details.

As soon as I have some other opinions I would create a proposed update.

**Comment by isaacsas** [comment]
"Using Catalyst" is an introduction to Catalyst for existing Julia users, so I'm not sure we need another tutorial in that regard. We probably don't want to get into having to have lots of tutorials that basically teach Julia to people; there are plenty of other resources for that we can just link to.

Adding an "Applications and Example Networks" or "Applications" and "Example Network" sections sounds fine, however, I'd keep the network analysis tutorial in the "Tutorials" section since it is a tutorial on Catalyst functionality, and not an illustration of a more complicated model or integrating with other tooling.

**Comment by isaacsas** [comment]
Having an advanced simulations options, or common simulation questions section that illustrates the stuff you mention sounds good to me.

**Comment by TorkelE** [comment]
Sorry, yes. "Using Catalyst" subsection would be moved to the initial one. And as I said I agree we only should have one subsection (the one that we already have) that is for introducing Catalyst (and Julia) to new Julia users, for exact the reason that you said.

I also think I always up the "Network Analysis" section as a Tutorial. It was the "Basic Chemical Reaction Network Examples" and possibly "Smoluchowski Coagulation Equation" that I suggested splitting off.

**Comment by TorkelE** [comment]
Yes
