### ISSUE TITLE
Enable symbolic manipulation of `u0` and `p` vector

### ISSUE THREAD

**Issue by TorkelE** [SciML/Catalyst.jl#582]
Currently, initial conditions and parameter values can be set symbolically, without assuming anything about their order within the vector:
```julia
rn = @reaction_network begin
    (p,d), 0 <--> X
    (p,d), 0 <--> Y
end p d
u0 = [:X => 1.0, :Y => 2.0]
p = [:p => 1.0, :d => 0.1]
```
unfortunately, it seems that in many cases, once some DiffEq problem is created, this information is lost. At that point, one has to use order to manipulate their values. Here follows some examples where I attempt various such modifications post-creation. As noted, most approaches fail.
```julia
using DifferentialEquations, ModelingToolkit, Catalyst, Plots

rn = @reaction_network begin
    (p,d), 0 <--> X
    (p,d), 0 <--> Y
end p d
u0 = [:X => 1.0, :Y => 2.0]
p = [:p => 1.0, :d => 0.1]

oprob = ODEProblem(rn,u0,(0.0,10.0),p)
sol = solve(oprob, Rosenbrock23())
plot(sol)


### Plot specific index. ###

plot(sol,idxs=1)    # Works.

plot(sol,idxs=[:X])    # ERROR: UndefVarError: X not defined

@variables X
plot(sol,idxs=[X])    # ERROR: ArgumentError: X is neither an observed nor a state variable.

plot(sol,idxs=[states(rn)[1]])    # Works.


### Remake an ODEProblem. ###

oprob1 = remake(oprob,p=[:p => 1.0, :d => 0.2])
oprob1.p    # Returns [1.0, 0.1], wrong.

oprob2 = remake(oprob,p=[1.0, 0.2])
oprob2.p    # Returns [1.0, 0.2], correct.

# Bothe these yield errors, but some syntax like this would be good.
oprob3 = remake(oprob,p.d=0.2)
oprob3 = remake(oprob,p[:d]=0.2)


### Modify integrator ###
affect1!(integrator) = integrator.p = [1.0, 0.5]
affect2!(integrator) = integrator.p = [:p => 1.0, :d => 0.5]
affect3!(integrator) = integrator.p.d = 0.5
affect4!(integrator) = integrator.p[:d] = 0.5

cb1 = PresetTimeCallback([5.0],affect1!)
cb2 = PresetTimeCallback([5.0],affect2!)
cb3 = PresetTimeCallback([5.0],affect3!)
cb4 = PresetTimeCallback([5.0],affect4!)

# Works
u01 = [:X => 1.0, :Y => 2.0]
p1 = [:p => 1.0, :d => 0.1]
oprob1 = ODEProblem(rn,u01,(0.0,10.0),p1)
sol1 = solve(oprob, Rosenbrock23(); callback=cb1)
plot(sol1)

# ERROR: MethodError: Cannot `convert` an object of type Pair{Symbol, Float64} to an object of type Float64
u02 = [:X => 1.0, :Y => 2.0]
p2 = [:p => 1.0, :d => 0.1]
oprob2 = ODEProblem(rn,u02,(0.0,10.0),p2)
sol2 = solve(oprob2, Rosenbrock23(); callback=cb2)
plot(sol2)

# ERROR: type Array has no field d
u03 = [:X => 1.0, :Y => 2.0]
p3 = [:p => 1.0, :d => 0.1]
oprob3 = ODEProblem(rn,u03,(0.0,10.0),p3)
sol3 = solve(oprob3, Rosenbrock23(); callback=cb3)
plot(sol3)

# ERROR: ArgumentError: invalid index: :d of type Symbol
u04 = [:X => 1.0, :Y => 2.0]
p4 = [:p => 1.0, :d => 0.1]
oprob4 = ODEProblem(rn,u04,(0.0,10.0),p4)
sol4 = solve(oprob4, Rosenbrock23(); callback=cb4)
plot(sol4)
```
Given that we are abandoning the use of ordering, we have to figure this out. This is likely mostly an MTK issue, but I am posting this here as a starter.

These tests were carried out using the following version:
```
(Julia Temporary Environment) pkg> status
Status `~/Desktop/Julia Temporary Environment/Project.toml`
  [479239e8] Catalyst v12.3.2
  [0c46a032] DifferentialEquations v7.6.0
  [961ee093] ModelingToolkit v8.42.0
  [91a5bcdd] Plots v1.38.2
```

**Comment by isaacsas** [comment]
You need to consistently use the symbolic variables associated with the problem that you can get via `sys.var` or `@unpack var = sys`. See https://docs.sciml.ai/Catalyst/dev/faqs/#How-to-index-solution-objects-using-symbolic-variables-and-observables?

**Comment by TorkelE** [comment]
Maybe I am missing something, but how would I modify the `integrator` in a callback, or call `remake` on my problem when I want to do an ensemble of different initial conditions?

Generally, if `u0=[:X=>1.0, :Y=>2,0]` is valid notation when creating an `ODEProblem`, it feels like an oversight that it is not when calling `remake` on it.

**Comment by isaacsas** [comment]
That's only valid if you pass a `ReactionSystem` to a problem because Catalyst intercepts and converts to symbolic variables. For any other ModelingToolkit system type a problem passed symbol maps won't work. The maps need to use symbolics. We can't really redefine `remake` and such in Catalyst; those are part of SciMLBase.

Now that the DSL will support initial conditions we should consider dropping support for symbol maps, and instead push people to specify initial conditions and such in the DSL or when using `@variables` / `@parameters` / `@species`.

`remake` requires symbolic maps, and `integrator`s should accept symbolic variables as indexing inputs.

Here is a `remake` example 
```julia
using Catalyst, DifferentialEquations, ModelingToolkit
@parameters β ν S0
@variables t S(t) I(t) R(t)
rx1 = Reaction(β, [S,I], [I], [1,1], [2])
rx2 = Reaction(ν, [I], [R])
defs = Dict([β => .0001, ν => .01, S0 => 999.0, S => S0, I => 1.0, R => 0.0])
@named sir = ReactionSystem([rx1,rx2],t,[S,I,R], [β,ν,S0]; defaults=defs)
odesys = convert(ODESystem, sir)
oprob = ODEProblem(odesys, Float64[], (0.0, 1000.0))
@assert  oprob.u0[1] == 999.0

getval(v) = defs[v]
pmap = parameters(odesys) .=> getval.(parameters(odesys))
u0map = states(odesys) .=> getval.(states(odesys))

# change S0 to 10.0
p = getval.(parameters(odesys))
p[end] = 10.0 

for (idx, param) in enumerate(p)
    pmap[idx] = pmap[idx][1] => param
end
oprob2 = remake(oprob; p=pmap, u0=u0map)
@assert oprob2.u0[1] == 10.0
```

**Comment by TorkelE** [comment]
I do not think I agree, but we can discuss it later since I am not sure I fully understand what you mean.

In your example, do you not use the assumption of order given that you change S0 through `p[end] = 10.0`?

**Comment by TorkelE** [comment]
Actually, just checking, when you say "symbolic maps" you mean using MTK variables or parameters in a vector of pairs to values, and when you use symbol map is a vector pairing symbols to values?

**Comment by isaacsas** [comment]
Yes, by symbol maps I mean `map = :A => 1.0`, while by symbolic maps I mean `@variables t A(t); map = A => 1.0`.

**Comment by isaacsas** [comment]
Here is a simpler example
```julia
using Catalyst, DifferentialEquations
rn = @reaction_network begin
           k, X --> 0
           end k
setdefaults!(rn, [:k => 10.0, :X => 10.0])
oprob = ODEProblem(rn, [], (0.0, 1.0))
sol = solve(oprob, Tsit5())
p = plot(sol)
@unpack X = rn
oprob2 = remake(oprob; u0 = [X => 5.0])
sol2 = solve(oprob2, Tsit5())
plot!(p, sol2, label="X2(t)")
```

**Comment by TorkelE** [comment]
Yes that's better. Would it be possible to use a similar interface to modify an `integrator`?

**Comment by isaacsas** [comment]
I think so: https://github.com/SciML/SciMLBase.jl/blob/master/test/downstream/integrator_indexing.jl

**Comment by TorkelE** [comment]
Thanks, will have a look at that.

**Comment by isaacsas** [comment]
@TorkelE I'm going to close this as this isn't really something to address within Catalyst, but more about integrators and problems at this point (and you've brought it up on those repos). Feel free to reopen if you think there is something we need to modify within Catalyst though!
