### ISSUE TITLE
drop mutating system extenders

### ISSUE THREAD

**Issue by isaacsas** [SciML/Catalyst.jl#583]
`@add_reactions`, `addparams!` and such can probably be dropped now that ModelingToolkit has an established API for extending and composing systems. We should just stick with pushing people to use those functions (I don't think we mention these in any tutorials currently).

**Comment by isaacsas** [comment]
I guess maybe we should also drop the macro to make a completely empty system? I'm not sure it serves any use if we drop the preceding functions.

**Comment by TorkelE** [comment]
Sounds good. I can make a PR tomorrow replacing their effect with deprecation warnings.

I think the biggest consequence is that there are quite a few tests that depend on these though. They should be removed or replaced with MTK stuff of similar function.

**Comment by isaacsas** [comment]
We should have tests on `extend` and `compose` in the compositional modeling test file, and those are what people should use. As far as I can tell we don't actually advertise these anywhere except in the API part of the docs. For now we can just move them to a separate old code file to keep them around in case we later on see a use case for having them.

I've finished going through the doc updates on your PR and am working my way through the DSL code updates. I may not get to going over the test updates till tomorrow, but I'm almost there.

**Comment by isaacsas** [comment]
We could properly give a deprecation warning for these but keep them around for now, and then drop them in the near future (since your PR updated them as needed anyways). That is a bit nicer to users than dropping them immediately (like we are doing with the old DSL notation).

**Comment by isaacsas** [comment]
i.e. use `Base.depwarn` like we do for `params` in the networkapi.jl file.

**Comment by isaacsas** [comment]
Keeping them for now since they were easy to update it seems.
