### ISSUE TITLE
Add documentation for chemistry related functionality

### ISSUE THREAD

**Issue by TorkelE** [SciML/Catalyst.jl#677]
The `compound` and reaction balancing functionality has been added in:
https://github.com/SciML/Catalyst.jl/pull/651
https://github.com/SciML/Catalyst.jl/pull/657
https://github.com/SciML/Catalyst.jl/pull/667
but are not yet documented, this should be added at some point.

**Comment by isaacsas** [comment]
@LalitChauhan56 are you still planning to do this?

**Comment by isaacsas** [comment]
Note that a basic tutorial would just introduce what I summarized in the HISTORY.md file.

**Comment by isaacsas** [comment]
Also, the macro and `balance_reaction` should get proper doc strings showing their usage and discussing what they return.

**Comment by TorkelE** [comment]
now works on master
