### ISSUE TITLE
Compounds don't support interpolation of variables

### ISSUE THREAD

**Issue by isaacsas** [SciML/Catalyst.jl#690]
Which means they are not usable programmatically within code. For example
```julia
@variables t
@species A(t) B(t)
a = A
@compound AB a B   # errors
@compound AB $a B   # errors
```
So there is no way for a user to have a species stored in a variable and get it into the `@compound` macro.

**Comment by TorkelE** [comment]
That's annoying. Thought we had that in the tests, but apparently missed to point this out properly when I suggested them.

**Comment by isaacsas** [comment]
I thought so too, and definitely mentioned it, but somehow it was apparently missed.

**Comment by TorkelE** [comment]
now works on master
