### ISSUE TITLE
Enable reaction specific additional data in DSL

### ISSUE THREAD

**Issue by TorkelE** [SciML/Catalyst.jl#693]
In the implementation of noise scaling (https://github.com/SciML/Catalyst.jl/pull/678), we allow the scaling of the noise in the CLE to be modulated independently for all reactions. In this case, each reaction is associated with one noise-scaling parameter. However, there is not good way to pair the information of which noise scaling parameter scales which reaction (so ordering is used). After discussion with @isaacsas it was suggested that something like:
```julia
@begin reaction_network
    @noise_scaling_parameters a b
    k1, 0 --> A, [noise=a]
    k2, B --> C  
    k3, A + B --> C, [noise=a]
    k4, C --> A + B, [noise=b]
end
```
would be useful. Here, for 3 of the reactions, we add a noise scaling parameter. We could also move additional information to this field, like instead of using `⇒` to disable massaction, we could make it a field:
```julia
@begin reaction_network
    @noise_scaling_parameters a b
    k1, 0 --> A, [noise=a]
    k2, B --> C  
    k3, A + B --> C, [noise=a, massaction=false]
    k4, C --> A + B, [noise=b]
end
```

Expansion of `[...]` information across bundles reactions would work identically to as rates do.

A similar way would be needed to add this kind of information when `Reaction` is called to create reactions programmatically (a kwarg?).

**Comment by isaacsas** [comment]
My one concern in thinking more about this becomes how to then control changing the scaling, for example if someone has a reaction arising from an SBML file how can they add a noise scaling to it. 

More generally I wonder if we really need a way to associate an id to a reaction/equation, and then we can have mappings from id to properties within systems which can be altered.

**Comment by TorkelE** [comment]
now works on master
