### ISSUE TITLE
Adding events macro to reaction network DSL

### ISSUE THREAD

**Issue by tstrey** [SciML/Catalyst.jl#694]
One possible way of doing this is the following: 
```julia
rn = @reaction_network rxs begin
     @variables t
     @parameters k
     @species A(t) B(t)

     k, A --> B
     @discrete_events begin
          (t == switch_time) => [B ~ 0.0]
     end
     @continuous_events begin
          (A < switch_time) => [B ~ 3.0]
     end
end
```
However, I think by having the macro inside `@reaction_network` you loose some flexibility. For example, if you wanted to use rn with different events. It could also be argued that conceptually a reaction network is how the species interact with each other but, the events, being external added boundary conditions, merging the two would not be a good idea.

**Comment by TorkelE** [comment]
now works on master
