### ISSUE TITLE
Reduce use of special characters in DSL in documentation (e.g. use "-->" instead of "→")

### ISSUE THREAD

**Issue by TorkelE** [SciML/Catalyst.jl#696]
When I wrote a lot of docs long time ago I typically used "∅" and "→" instead of "0" and "-->", and in the docs as well. Now I am wondering whether we should just uniformly use the simpler "0" and "-->" instead (except for the part where we show that the special version are possible.

I don't have any strong opinions, but and currently using "0" and "-->" in new stuff I write. @isaacsas If you prefer it that way I'm happy to change to these version next time I go through and make a doc change.

**Comment by isaacsas** [comment]
Yes, minimizing Unicode arrow / symbol use in tutorials sounds like a good idea.

**Comment by isaacsas** [comment]
Though I personally like using null over zero for display purposes since it is closer to what one writes in practice.

**Comment by TorkelE** [comment]
Empty set still used, but all arrows are fixed in https://github.com/SciML/Catalyst.jl/pull/715. I think this is good now.
