### ISSUE TITLE
New Julia user tutorial should start with creating an empty environment

### ISSUE THREAD

**Issue by isaacsas** [SciML/Catalyst.jl#722]
For new users, it is easy to add lots of packages in the default scope and end up with out of date packages holding things back, see

https://discourse.julialang.org/t/unable-to-reproduce-catalyst-jl-example/106099/15

We should consider starting the tutorial for new users, and maybe even the tutorial for advanced users, with a short section that suggests creating a new environment and adding the relevant packages for the tutorial only (explaining why this is considered good practice). Then we can give the commands via `Pkg.` to install the needed tutorial libraries.

**Comment by ChrisRackauckas** [comment]
I wonder if we should do this at the SciML level. We basically just copy-paste the same installation instructions into the same repo. Maybe they should be a bit more precise, like we should say "make and environment and add ..., for more information see ..." and maybe point to https://docs.sciml.ai/Overview/stable/getting_started/installation/ with an extended discussion on package environments?

**Comment by TorkelE** [comment]
This makes sense, agreed. Will add it to the list.

**Comment by isaacsas** [comment]
I think it makes sense to have at the SciML level too (we can always say it is not required but recommended for the following reasons…).

**Comment by TorkelE** [comment]
Having a more extensive SciML intro (something like https://docs.sciml.ai/Overview/stable/getting_started/installation/) would be useful, and we could link there (although we already link to a couple of general Julia stuff). Then we could have a section in the Catalyst intro tutorial describing the issue and how to do, and link to SciML for more general details.

**Comment by TorkelE** [comment]
now works on master
