### ISSUE TITLE
Conversion to non-linear system does not handle presence of differential equations:

### ISSUE THREAD

**Issue by TorkelE** [SciML/Catalyst.jl#727]
This code:
```julia
@parameters v1 K1 v2=1.0 K2=0.4 d
@variables t Y(t)
@species X(t)
eq = Differential(Y) ~ v1*Y/(Y+K1) - d*Y
rx1 = @reaction v1*$Y/($Y+K1), 0 --> X
rx2 = @reaction d, X --> 0
@named rn = ReactionSystem([rx1, rx2, eq], t)

ns = convert(NonlinearSystem, rn);
println.(ns.eqs)
```
returns
```julia
0 ~ (v1*Y(t)) / (K1 + Y(t)) - d*X(t)
Differential(Y(t)) ~ (v1*Y(t)) / (K1 + Y(t)) - d*Y(t)
```
However, the `Differential(Y(t))` should be set to 0.

**Comment by isaacsas** [comment]
We don't handle conversion of non-reactions currently, but assume the user has input them as they desired in their model. So that would need to be added by someone, presumably it can reuse what is done in MTK.

**Comment by isaacsas** [comment]
@TorkelE this is handled now? (Modulo recent bugs via Symbolics changes?)

**Comment by TorkelE** [comment]
yes, this is handled now
