### ISSUE TITLE
Improve documentation of `remove_conserved` when creating an `ODESystem` - and make it default to `true`?

### ISSUE THREAD

**Issue by ranocha** [SciML/Catalyst.jl#773]
We have just discussed this on Slack. See https://docs.sciml.ai/Catalyst/stable/faqs/#How-to-index-solution-objects-using-symbolic-variables-and-observables?

**Comment by isaacsas** [comment]
Yeah, somehow we never got this more at the fore-front as a feature even though it is in the docs in several places:

https://docs.sciml.ai/Catalyst/stable/catalyst_applications/homotopy_continuation/#Systems-with-conservation-laws

https://docs.sciml.ai/Catalyst/stable/faqs/#How-to-index-solution-objects-using-symbolic-variables-and-observables?

**Comment by isaacsas** [comment]
@TorkelE what do you think about defaulting it to true? I know we've discussed but I can't remember if you had a reason not to do it by default for ODEs?

**Comment by ChrisRackauckas** [comment]
I don't see a reason to not make it true. Enforcing conservation generally makes the numerics more stable, and structural simplify should then eliminate the equations anyways so we'd get smaller simpler equations to solve.

**Comment by isaacsas** [comment]
OK, we can go with it always being true for ODE models.
