### ISSUE TITLE
The `complete` field is a `Num`?

### ISSUE THREAD

**Issue by TorkelE** [SciML/Catalyst.jl#782]
On the latest version: 
```julia
using Catalyst

rs = @reaction_network begin
    d, X --> 0
end

rs.complete    # Gives `false`.
rs.complete |> typeof    # Gives `Num`.
```

Should be a `Bool`, no idea why it is not though.

**Comment by isaacsas** [comment]
MTK systems should never have their fields accessed directly as they overload `getproperty`. Use `ModelingToolkit.iscomplete(rs)`.

**Comment by TorkelE** [comment]
Thanks, I first tried `iscompelte` but didn't work, `ModelingToolkit.iscomplete(rs)`.

Still doesn't really make sense though?

**Comment by isaacsas** [comment]
MTK overloads all fields assuming you are trying to access a symbolic variable named `complete`, i.e. `rs.complete`, instead of a field of the system. You need to use `getfield` if you really want to access a system field directly (but you should use the MTK accessors instead anyways).

**Comment by TorkelE** [comment]
I see, yeah that makes total sense, thanks a lot!
