### ISSUE TITLE
`@register` ambiguity

### ISSUE THREAD

**Issue by ArnoStrouwen** [SciML/Catalyst.jl#788]
Strange ambiguity pops up, even though `@register` is nowhere used.
I tried the same in Symbolics, SymbolicUtils and ModelingToolkit and did not find the same behavior there.
```jl
julia> using Catalyst
julia> using Test
julia> Test.detect_ambiguities(Catalyst)
WARNING: using deprecated binding Symbolics.@register in Catalyst.
, use @register_symbolic instead.
Catalyst.@register is deprecated, use Symbolics.@register_symbolic instead.
ERROR: use of deprecated variable: Catalyst.@register
Stacktrace:
 [1] detect_ambiguities(mods::Module; recursive::Bool, ambiguous_bottom::Bool, allowed_undefineds::Any)
   @ Test C:\Users\arno\.julia\juliaup\julia-1.10.0+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Test\src\Test.jl:1968
 [2] detect_ambiguities(mods::Module)
   @ Test C:\Users\arno\.julia\juliaup\julia-1.10.0+0.x64.w64.mingw32\share\julia\stdlib\v1.10\Test\src\Test.jl:1921
 [3] top-level scope
   @ REPL[4]:1
```

I do not understand how it gets past:
https://github.com/JuliaLang/julia/blob/master/stdlib/Test/src/Test.jl#L2078
Since:
```jl
julia> Base.isdeprecated(Catalyst, Symbol("@register"))
true
```

**Comment by isaacsas** [comment]
Is there something actionable here? Searching on Github I don't see that we use `@register` anywhere?

**Comment by ArnoStrouwen** [comment]
Does not seem actionable to me, but not sure where else to report it. I'm not certain this is a Julia bug.

**Comment by isaacsas** [comment]
I don’t get this warning in a clean environment with the latest Catalyst on 1.10. Are you using an older version?

**Comment by ArnoStrouwen** [comment]
Yes, I'm on the latest. Did you run with `julia --depwarn=error`?
The end goal is to switch that on for all of SciML testing.

**Comment by ChrisRackauckas** [comment]
Has it been a deprecation long enough to just make it error now? A release with that as an error would be a clear trigger.

**Comment by isaacsas** [comment]
Very weird, thanks for checking!

**Comment by isaacsas** [comment]
If there is a change we need to make here I'm happy to, but have no idea what is causing this (in Catalyst).

**Comment by ArnoStrouwen** [comment]
https://github.com/JuliaSymbolics/Symbolics.jl/pull/1071 solves this.
