### ISSUE TITLE
Miscomputation when using a stoichiometric coefficient != 1

### ISSUE THREAD

**Issue by odurif1** [SciML/Catalyst.jl#802]
version=Catalyst v13.5.1

The result is incorrect when computing a simple chemical reaction 2A -> B 

It seems to be an issue when using a stoichiometric coefficient != 1

**Example**

```julia

rn = @reaction_network begin
    k1, 2A --> B
end

k = [
    :k1 => 2.1e-13
]

u0 = [
    :A => 2.8e10,
    :B => 0
]

tspan = (0.0,10.0)
op    = ODEProblem(rn, u0, tspan, k)
sol   = solve(op)

```

Bellow a plot comparing this numerical result with the analytical solution:  $`\ f(t)=\dfrac{1}{(2 k_1 t+1/[A]_0)}  `$

![test](https://github.com/SciML/Catalyst.jl/assets/158311584/4f8877ef-3146-4add-923c-163095e4f7fc)

**Comment by isaacsas** [comment]
Have you read https://docs.sciml.ai/Catalyst/stable/introduction_to_catalyst/introduction_to_catalyst/#Reaction-rate-laws-used-in-simulations

 Catalyst assumes microscopic rates by default, so your rate might differ by a factor of two from what you are expecting. You can turn this off as described in that section.

**Comment by odurif1** [comment]
Thank you, it is exactly a factor two, and  my issue is solved using _combinatoric_ratelaws=false_

```julia
ODEProblem(rn, u0, tspan, k; combinatoric_ratelaws=false)
```

I did not knew this subtility between _microscopic rates_  and  _transition rate_ . Out of curiosity, why  is _combinatoric_ratelaws=false_ is set to _true_ by default ?

**Comment by isaacsas** [comment]
We decided to use the physical interpretation that is common for stochastic jump process models, our most microscopic supported model, by default. The rate has a clear physical meaning at that level, i.e. the probability per time one random set of substrates can react. We then used this interpretation for all mathematical model types to ensure they are comparable. 

You can also disable this as a keyword argument to `ReactionSystem`,  unfortunately we haven’t added support for disabling it in the DSL yet. @TorkelE we should probably add a DSL option to set this keyword argument to ensure the DSL fully supports all ReactionSystem features.

**Comment by odurif1** [comment]
Thanks a lot for your help. I am making a mental picture but personally, I found this very confusing, certainly because I am not used to this approach.

In chemical kinetics the system $` 2 A \rightarrow A_2 `$ is written as:

$`  \frac{d[A]}{dt} = - 2 k [A]^2 `$ following the reactant
or  $`  \frac{d[A_2]}{dt} = k [A_2] `$ following the product

It is written this way because the physical interpretation is here straightforward, 2 $` A `$ are consumed when one $`  A _2 `$ is produced. However, the rate coefficient $` k `$ is the same whether you consider the reactant or the product because it is the same reaction.

In the _microscopic_ approach employed here, the rate coefficient has to be twice higher when considering the reactant compared to the product. Thus we would have to consider not one rate coefficient for this reaction but two differents, which makes things, to my point of view, confusing.



But let me thank you for this wonderful and easy-to-use Julia package!
