### ISSUE TITLE
Weird inconsistency for Jump simulations declared with/without Catalyst

### ISSUE THREAD

**Issue by TorkelE** [SciML/Catalyst.jl#803]
I encountered this one while improving some of the jump simulation tests. I have tried to make the example as simple as possible.

Here, I declare a model manually and using Catalyst. If everything works well, when simulated using the same seed, they should yield identical output. I have looked a lot at the model declarations, they should be identical (but maybe fresh eyes will catch something).

The weird part is that, for some seeds the simulations are indeed identical. For some, they are not. Surely, the likelihood that two different models should yield identical jumps is nonexistence. Either all seeds should yield identical simulations, or all should not?

Example:
```julia
# Fetch packages.
using Catalyst, JumpProcesses, StableRNGs

# Sets a stable rng.
rng = StableRNG(12345)

# Creates a function which generates catalyst/manual-based model declaration simulations.
# The input is a single seed.
function make_sims(seed)
    # Creates the model with Catalyst.
    rn_catalyst = @reaction_network rnh7 begin
        hill(X1, v, K, n), ∅ → X1
        d, X1 → ∅
    end

    # Creates the model manually.
    rate_1(u, p, t) = p[1] * (u[1]^p[3]) / (u[1]^p[3] + p[2]^p[3])
    rate_2(u, p, t) = p[4] * u[1]
    affect_1!(integrator) = (integrator.u[1] += 1)
    affect_2!(integrator) = (integrator.u[1] -= 1)
    jump_1 = ConstantRateJump(rate_1, affect_1!)
    jump_2 = ConstantRateJump(rate_2, affect_2!)
    rn_manual = (jump_1, jump_2)

    # Simulates the Catalyst-created model.
    u0_1 = [:X1 => 5]
    ps_1 = [:v => 0.025, :K => 0.04, :n => 0.025, :d => 0.05]
    dprob_1 = DiscreteProblem(rn_catalyst, u0_1, (0.0, 100.0), ps_1)
    jprob_1 = JumpProblem(rn_catalyst, dprob_1, Direct(); rng)
    sol1 = solve(jprob_1, SSAStepper(); seed)

    # Simulates the manually created model.
    u0_2 = last.(u0_1)
    ps_2 = last.(ps_1)
    dprob_2 = DiscreteProblem(u0_2, (0.0, 100.0), ps_2)
    jprob_2 = JumpProblem(dprob_2, Direct(), rn_manual...; rng)
    sol2 = solve(jprob_2, SSAStepper(); seed)

    #returns the two solutions.
    return sol1, sol2
end
```
Now, for `seed = 47` the simulations are indeed identical:
```julia
sim1_seed47, sim2_seed47 = make_sims(47)
sim1_seed47[[:X1]] == sim2_seed47.u  # returns `true`
sim1_seed47.t == sim2_seed47.t  # returns `true`
```
I can confirm this in a plot:
```julia
using Plots
plot(plot(sim1_seed47), plot(sim2_seed47))
```
![image](https://github.com/SciML/Catalyst.jl/assets/18099310/b6b84875-37a9-4f9c-aac6-6a2e3e2bb960)

However, for `seed = 13` I get different simulations:
```julia
sim1_seed13, sim2_seed13 = make_sims(12)
sim1_seed13[[:X1]] == sim2_seed13.u  # returns `false`
sim1_seed13.t == sim2_seed13.t  # returns `false`
plot(plot(sim1_seed13), plot(sim2_seed13))
```
![image](https://github.com/SciML/Catalyst.jl/assets/18099310/66b67573-9978-4cbc-81eb-4d3152f3c6ef)

This only seems to be a problem for some Catalyst models. Most, never have this problem (or from what I can tell) even if I simulate for tons of different seeds. I think I have seen this in another model without distinguishing features (but I think they started passing the tests, and now I cannot exactly remember which one it was)

**Comment by isaacsas** [comment]
One thing to note is your models aren't really completely the same at the JumpProcess level as you are using two ConstantRateJumps by hand but Catalyst will generate on ConstantRateJump and one MassActionJump. Direct will sample them by searching over MassActionJumps then ConstantRate jumps, so you may be flipping their order (though I'm not sure why you get the same results then for most seeds).

**Comment by isaacsas** [comment]
This is why it is better to compare a statistic over many simulations rather than trying to get identical results with different input formats for one path.

**Comment by TorkelE** [comment]
Ok, didn't know that there was such a potential problem. Will see if it works using mass action. 

I think both methods have merit and we should use both.

**Comment by isaacsas** [comment]
I don't think we should use this method -- it is relying on internal details of other packages, i.e. MTK and StochasticDiffEq/JumpProcesses, to generate truly identical input. It could therefore break at any time should they change something in their codegen (i.e. ordering of jumps for example).

**Comment by TorkelE** [comment]
But presumably this is the promise of the `seed`? I am checking this case, but it seems I failed to recreate what Catalyst sends to JupProcesses, which is on me.

I use statistics like that for e.g. the noise scaling, however, those simulations (and when we try for jump simulations) do take time. Using the seed approach allow us to tests a much larger amount of cases than just collecting statistics does. 

That said I agree with your point, and that when we use seeds we should know what we are doing.

**Comment by TorkelE** [comment]
I can confirm that using a MassActionJump seems to solve this, thanks!
