### ISSUE TITLE
v14 tests broken

### ISSUE THREAD

**Issue by isaacsas** [SciML/Catalyst.jl#824]
https://github.com/SciML/Catalyst.jl/actions/runs/9063058490/job/24898215803?pr=823#step:6:1804

This seems due to using `replace` from Symbolics, which is not exported and probably shouldn't be used.

I have marked the relevant tests as broken for now.

CC: @TorkelE

**Comment by isaacsas** [comment]
The following tests are being disabled due to this bug in https://github.com/SciML/Catalyst.jl/pull/823 and should be added back as part of fixing this:

```julia
@time @safetestset "Coupled CRN/Equation Systems" begin include("reactionsystem_structure/coupled_equation_reaction_systems.jl") end

@time @safetestset "BifurcationKit Extension" begin include("extensions/bifurcation_kit.jl") end

@time @safetestset "HomotopyContinuation Extension" begin include("extensions/homotopy_continuation.jl") end

@time @safetestset "Structural Identifiability Extension" begin include("extensions/structural_identifiability.jl") end
```

**Comment by isaacsas** [comment]
I think this is now fixed, but @TorkelE feel free to reopen if it isn't.

**Comment by TorkelE** [comment]
yes, all fixed
