### ISSUE TITLE
incorrect Float64 assumptions in diff_to_zero

### ISSUE THREAD

**Issue by isaacsas** [SciML/Catalyst.jl#825]
https://github.com/SciML/Catalyst.jl/blob/2276e1cbd53d8ade2b7b2b6d822ab7df50fa3a53/src/reactionsystem.jl#L1632

seems problematic. We shouldn't be assuming a type. This whole code path should probably just delete the derivative terms instead of setting them to zero to avoid making assumptions about types.

**Comment by TorkelE** [comment]
Solved (as good as can be done without a major overhaul at least) by https://github.com/SciML/Catalyst.jl/pull/892
