### ISSUE TITLE
don't use internal Symbolics.jl functions

### ISSUE THREAD

**Issue by isaacsas** [SciML/Catalyst.jl#826]
https://github.com/SciML/Catalyst.jl/blob/2276e1cbd53d8ade2b7b2b6d822ab7df50fa3a53/src/reactionsystem.jl#L1626

we shouldn't be using what seems likely to be a truly internal Symbolics function that could change at any time as in that code.

**Comment by TorkelE** [comment]
fixed by https://github.com/SciML/Catalyst.jl/pull/887
