### ISSUE TITLE
Reorganisations/renamings to the docs

### ISSUE THREAD

**Issue by TorkelE** [SciML/Catalyst.jl#837]
List of updates to consider to the doc (which does not involve changing the actual pages.
- [ ] Less generic name for "Model Simulation" section. List of alternatives: "Time Course Simulations".
- [ ] Split Model properties documentation from the Model creation ones. These doc pages: "Network Analysis", "Model Visualisation", and "Chemistry Functionality" should ideally be in a different section, in case we can come up with a fitting title.

**Comment by isaacsas** [comment]
Compounds are a basic model specification property though, so I'd say they should be handled in model construction sections.

**Comment by TorkelE** [comment]
I agree with that. I am not really fond of the current merging of the model properties and model construction bit, but it really is not something we should prioritise either. At some point we might come up with a better way to do it (probably promoted by new features, requiring more docs). Right now, letting things be as they are is probably the sensible thing to do though.
