### ISSUE TITLE
Network analysis algorithms 

### ISSUE THREAD

**Issue by vyudu** [SciML/Catalyst.jl#840]
Hi all, this summer I'm planning on adding a lot of graph/network analysis features relevant for chemical reaction networks to Catalyst. A smattering of things this might include:  

- Detecting [concordance](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4679294/) in a reaction network
- Detecting [persistence](https://arxiv.org/pdf/1810.00225) in a reaction network
- Detecting autocatalysis, particularly [self-replicable siphons](https://arxiv.org/abs/1309.3957), in a reaction network (and perhaps other things related to programmability) 
- Detecting [bistability](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-021-04477-x) in a reaction network
- Detecting [absolute concentration robustness](https://arxiv.org/pdf/2401.00078)
- Adding a "network summary" that tells you about relevant features at-a-glance

Let me know if people have other suggestions - I would like to focus on functionality that would be useful for practicing chemists/systems biologists, but am not super familiar with this literature. My focus over the next few weeks will be adding algorithms for different properties, rather than the summary/UI side, but if people have suggestions for the latter I'm also happy to hear them.

**Comment by isaacsas** [comment]
These look great to me!

**Comment by vyudu** [comment]
Methodology for the persistence check: 

1. Detect the set of minimal siphons in the reaction network, following [Shiu et al., 2009](https://people.tamu.edu/~annejls/SiphonsInCRNs.pdf)
2. Check necessary and sufficient conditions for persistence outlined in [Angeli et al., 2007](http://www.sontaglab.org/FTPDIR/angeli_leenheer_sontag_math_biosciences_MBS-D-06-00188R1.pdf): a network is persistent iff it is consistent (has right null eigenvector), conservative (has left null eigenvector), and all of its siphons are not critical (i.e. they contain the support of a conservation law)

**Comment by isaacsas** [comment]
Persistence reference: "On Enumerating Minimal Siphons in Petri nets using CLP and SAT solvers: Theoretical and Practical
Complexity"

**Comment by vyudu** [comment]
[Absolute concentration robustness](https://arxiv.org/pdf/2401.00078)
[Higher deficiency algorithm and others](https://etd.ohiolink.edu/acprod/odb_etd/ws/send_file/send?accession=osu1307122057&disposition=inline)
[Monotone Systems will not have multistationarity](https://arxiv.org/abs/1411.2896)
