### ISSUE TITLE
Typo in `HomotopyContinuation` docs tutorial

### ISSUE THREAD

**Issue by jonathanfischer97** [SciML/Catalyst.jl#860]
Apologies if this is already on the docs update agenda, but noticed a small typo on line 54 of `homotopy_continuation.md`:

## Problem

The example code block here gives `u0` without its keyword key:
```julia
ps = [:k1 => 2.0, :k2 => 1.0]
u0 = [:X1 => 1.0, :X2 => 1.0]
hc_steady_states(two_state_model, ps; u0)
``` 
which for some systems will give this error:
```julia
ERROR: The system has conservation laws but initial conditions were not provided for some species.
Stacktrace:
``` 

## Solution
Should be corrected to:
```julia
ps = [:k1 => 2.0, :k2 => 1.0]
u0 = [:X1 => 1.0, :X2 => 1.0]
hc_steady_states(two_state_model, ps; u0 = u0)
```

**Comment by TorkelE** [comment]
What versions are you working on? For me, this
```julia
using Catalyst
import HomotopyContinuation

two_state_model = @reaction_network begin
    (k1,k2), X1 <--> X2
end

ps = [:k1 => 2.0, :k2 => 1.0]
u0 = [:X1 => 1.0, :X2 => 1.0]
hc_steady_states(two_state_model, ps; u0)
```
works with
```
pkg> st
Status `~/Desktop/Julia Playground/Environment - Temporary/Project.toml`
  [479239e8] Catalyst v13.5.1
  [f213a82b] HomotopyContinuation v2.9.3
```

Generally, I think you can give kwargs without `=` if the name of the input variable is the same as the kwarg (i.e. like above), although I have not been using this for long so not super familiar with if there are more to it.

**Comment by jonathanfischer97** [comment]
You're absolutely right, I just ran it fine. 

Don't know what I did earlier to get the error, apologies.

**Comment by TorkelE** [comment]
no worries, thanks for reporting stuff that you see
