### ISSUE TITLE
Remove `using DifferentialEquations` from the docs

### ISSUE THREAD

**Issue by TorkelE** [SciML/Catalyst.jl#872]
I have tried to move to just using OrdinaryDiffEq in stuff that I have changed, but there are a couple of places left (FAQ, API, and some model examples).

**Comment by ChrisRackauckas** [comment]
In the latest release, OrdinaryDiffEq has the default method.

**Comment by isaacsas** [comment]
Awesome!

**Comment by TorkelE** [comment]
fixed on master
