### ISSUE TITLE
Display issues for vector variables/parameters in Latexify

### ISSUE THREAD

**Issue by TorkelE** [SciML/Catalyst.jl#932]
Simple example:
```julia
using Catalyst
@reaction_network begin
    @parameters k[1:2]
    @species (X(t))[1:2]
    (k[1],k[2]), X[1] <--> X[2]
end
```
produces:
![image](https://github.com/SciML/Catalyst.jl/assets/18099310/d257e581-15fb-4df9-a199-255e4ccb9023)

Here:
- For parameters we get *getindex(k,i)* instead of *k_i*
- For Species, *i* is dropped entirely.

Quite a couple of things happens if we change around so that species appear in rates and parameters as reactants:
```julia
@reaction_network begin
    @parameters k[1:2] [isconstantspecies=true]
    @species (X(t))[1:2]
    (X[1],X[2]), k[1] <--> k[2]
end
```
![image](https://github.com/SciML/Catalyst.jl/assets/18099310/0f736dee-34d0-4fae-bfb5-5018f07733a0)

Another vector-variable elated issue, which affects Symbolics and it is useful to keep track of, is https://github.com/JuliaSymbolics/Symbolics.jl/issues/1167

**Comment by isaacsas** [comment]
This seems fixed with the current release.
