### ISSUE TITLE
Add equations to the docs

### ISSUE THREAD

**Issue by lockwo** [SciML/Catalyst.jl#978]
It would be beneficial to have the basic equations for what the ODE/SDE systems are actually getting converted into in the docs. For example, just put eq 23 of https://homepages.inf.ed.ac.uk/stg/research/stochasticsimulation/papers/JChemPhys_113_297.pdf for the SDE system

**Comment by lockwo** [comment]
The reaction DSL could perhaps just have the SDE case along with the existing ODE case

**Comment by TorkelE** [comment]
There is an equation here: https://docs.sciml.ai/Catalyst/dev/introduction_to_catalyst/introduction_to_catalyst/#Chemical-Langevin-equation-(CLE)-stochastic-differential-equation-(SDE)-models, but increasing visibility for stuff like this would probably make sense. We had a plan on also adding a dedicated theory section that goes through stuff like this properly, but wouldn't be certain when that would actually be ready.

Not sure what you mean with
> The reaction DSL could perhaps just have the SDE case along with the existing ODE case

**Comment by isaacsas** [comment]
I think adding a section that complements the rate law section by showing the equations makes sense. We can then link it there and have it as a standalone page. It would be good to both give general formulas and some specific examples there.

**Comment by TorkelE** [comment]
Agreed. I remember when I read through the literature for my PhD, it was surprisingly hard to find a good resource which simply listed all the various equations derived from CRNs in a straightforward manner. Creating such a resource would probably be beneficial to the community. Also then using it as a link makes loads of sense, yeah, I think that could become very good.

**Comment by isaacsas** [comment]
It is worth mentioning that we don't exactly in the SDE case generate equation (23), we generate the analogoue of (23) but using the ODE rate laws in place of the propensities. I opened another issue about adding (23) as an option to generate too.

**Comment by lockwo** [comment]
Thanks for the quick PR!
