### ISSUE TITLE
Add missing model acces functions to API (and add links to it where functions are mentioned)

### ISSUE THREAD

**Issue by TorkelE** [SciML/Catalyst.jl#990]
Quite a few functions do not have their docstrings printed in the API, here is some I caught from the latest tutorial on adding model functions.
```equations
get_systems
parameters
get_species
get_ps`
get_unknowns
unknowns
get_observed
observed
get_rxs
```

**Comment by isaacsas** [comment]
I've also been wondering if for consistency we should add `get_reactions` and give `get_rxs` a deprecation warning for our next breaking release. The former seems more consistent with `reactions(rn)`.

**Comment by TorkelE** [comment]
That would make sense. In my tutorial I even mistakenly wrote `get_reactions` in one place, and later caught it and changed to `get_rxs`.

**Comment by TorkelE** [comment]
Turns out that, expect of `get_rxs` and `get_species` (which we have docstrings for in Catalyst), MTK lacks docstrings for these (at least what I could tell). This is likely why they were left out in the first place as well.
