### ISSUE TITLE
Fix long doc build time for single figure in intro to Catalyst

### ISSUE THREAD

**Issue by TorkelE** [SciML/Catalyst.jl#994]
This figure in the introduction to the docs:
![image](https://github.com/user-attachments/assets/fac5c0a1-3efb-4067-baee-8dca7e938022)
still causes really long doc build times. 

Changing the code block to
```julia
plot(sol)
plot(sol, density = 10000, fmt = :png) # hide
nothing # hide
```
reduced doc build time from 700-800 seconds to around 150 (after the first run which compiles stuff). Just reducing the `density` did not necessarily seem to have that effect though.

Does not need to be fixed soon, and I am not sure what the best approach is, but would be nice to figure out at some point since it makes writing documentation a lot more annoying.

**Comment by isaacsas** [comment]
This seems like a documenter bug — it seems to be ignoring the request in the doc to plot this as a png and is still plotting it as a svg.

**Comment by isaacsas** [comment]
We shouldn’t reduce the density — it leads to a very misleading plot that does not correctly illustrate the noise in the model.

**Comment by TorkelE** [comment]
I checked the plots with/without density and looked fine, but if you saw a difference then Ok.

**Comment by TorkelE** [comment]
The Documenter people suggest that the solution my be to use DisplayAs.jl, and that might work better than simply designating `:png` in the `plot` command. https://tkf.github.io/DisplayAs.jl/dev/#DisplayAs.PNG

**Comment by isaacsas** [comment]
Closed https://github.com/SciML/Catalyst.jl/pull/1006
