### ISSUE TITLE
Avoid using `prettyurl` in doc building

### ISSUE THREAD

**Issue by TorkelE** [SciML/Catalyst.jl#996]
Had some problems (now worked around) when trying to get animations to work. However, the person who pointed out the source of my problem also mentioned that use of this (which we do) is discouraged): https://github.com/JuliaDocs/Documenter.jl/pull/2402

**Comment by isaacsas** [comment]
The solution they give there is pretty unfriendly for developing docs. Having to run a local web server just to view the doc builds seems like a no go for me.

**Comment by TorkelE** [comment]
not sure how easy it is, but could be annoying. Seems odd that this is a thing and related to the prettyurl's though. I guess there is little hope in them changing things around though.

**Comment by isaacsas** [comment]
What if you make mp4s instead of gifs? (I assume you are currently making gifs?)

**Comment by TorkelE** [comment]
no mp4s. I found a workaround with displaying them directly in markdown, instead of as HTML which worked. The main point here really was that we were doing something that the documented people explicitly discouraged, but if you feel confident in it I feel confident in it too.

**Comment by isaacsas** [comment]
Sometimes Documenter devs advocate more complicated, less desirable, workflows to avoid an issue they don't want to address in Documenter (or is perhaps hard for them to figure out how to address cleanly). While having workarounds is helpful, if it makes developing documentation more complicated the recommended solutions may not be worth it.

**Comment by isaacsas** [comment]
(Also, we are using the SciML standard setting, so this would really need a SciML-wide modification, which I imagine won't happen until a solution exists that doesn't require one to run a web-server to view docs locally...)

**Comment by TorkelE** [comment]
> Sometimes one advocates more complicated, less desirable, workflows to avoid an issue they don't want to address (or is perhaps hard for one to figure out how to address cleanly). While having workarounds is helpful, if it makes developing documentation more complicated the recommended solutions may not be worth it.

Sounds good, yeah building live server sounds messy. Figured it might be worth looking into, but happy to go ahead like this.
